""" Build sources.bib and sources.md for the DA and AI review from verified metadata.

The approved references (reading_list.md after JXP's review, DA33-DA39) are listed in
ENTRIES below with their key, identifier and the local annotations (sections served,
what the entry supports, flags, AI taxonomy notes).  Everything bibliographic (author
lists, title, journal, volume, issue, pages or article number, year) is taken from the
Crossref works API for DOIs and from the arXiv API for preprints, never typed from
memory.  Every DOI is re-resolved with `curl -sI https://doi.org/<doi>` and the HTTP
code and access date are recorded; arXiv IDs are checked by title against the API.
Grey items (web pages, repositories) carry the fields given here plus the HTTP code
their URL returned today.

Output: ../sources.bib and ../sources.md (El Nino 2026 form: header paragraph with the
verification convention, entries numbered within topical groups, BibTeX keys shared
between the two files).  Crossref/arXiv responses are cached in a temp directory so
the script can be rerun cheaply; --no-cache refetches everything, which is what a
re-verification run should do.  Every run re-resolves every DOI and URL, so the access
date written into both files (urldate, "HTTP xxx on <date>") is the date of the run;
VERIFIED_ON keeps the list of dates on which the whole list was resolved, and the
sources.md header prints it.

History: first run 2026-09-22 (prompts #2-#3, 61 entries); rerun 2026-09-23 (prompt #3
completion, --no-cache) after JXP's answers DA40-DA44: PDFs of bonavita2020machine,
zanna2020data and the published fablet2021learning added, their AI notes rewritten
from the full text, FuXi-DA's note fixed to the Methods split (DA43).

Usage (ocean14):
    conda run -n ocean14 python reports/data_assimilation/scripts/build_bib.py [--no-cache]

Generated by JXP and Claude
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIB_PATH = os.path.join(REPORT_DIR, 'sources.bib')
MD_PATH = os.path.join(REPORT_DIR, 'sources.md')
CACHE = os.path.join(tempfile.gettempdir(), 'boonus_da_bib_cache')
UA = {'User-Agent': 'BOONUS-DA-review/0.1 (mailto:jxp@ucsc.edu)'}
TODAY = datetime.date.today().isoformat()
# Dates on which this script resolved every DOI and URL in the list (append on rerun).
VERIFIED_ON = ['2026-09-22', '2026-09-23']
if TODAY not in VERIFIED_ON:
    VERIFIED_ON.append(TODAY)

# ----------------------------------------------------------------------------------
# The approved list.  kind: article | incollection | arxiv | grey.
# flags: preprint, grey, optional.  pdf: file in context/da/ (private) if in hand.
# ----------------------------------------------------------------------------------
GROUPS = [
    ('A', 'Anchors and reviews'),
    ('B', 'Classical methods and the primer'),
    ('C', 'Global systems'),
    ('D', 'Regional and coastal systems'),
    ('E', 'Glider-specific data assimilation'),
    ('F', 'AI in numerical weather prediction'),
    ('G', 'AI in ocean data assimilation'),
    ('H', 'Biogeochemical data assimilation'),
]

ENTRIES = [
    # ---- A. Anchors and reviews -------------------------------------------------
    dict(key='moore2019synthesis', group='A', kind='article', doi='10.3389/fmars.2019.00090',
         pdf='moore2019.pdf', pdf_kind='publisher PDF',
         sections='3, 4, 5', supports='The GODAE OceanView community statement of what '
         'operational ocean DA does: the variational and ensemble families, the shared '
         'problems (B, R, bias, initialization shock) and the future list (hybrids, coupled '
         'DA, gliders and SWOT). The frame for Sections 3-5.'),
    dict(key='carrassi2018data', group='A', kind='article', doi='10.1002/wcc.535',
         arxiv='1709.02798', pdf='carrassi2018.pdf', pdf_kind='arXiv copy',
         sections='2 (primer), 3', supports='The derivations behind the boxed primer: '
         'Bayesian formulation, Kalman filter and smoother, 3D/4D-Var, EnKF variants, EnVar '
         'hybrids, localization and inflation; the TOPAZ operational EnKF example.'),
    dict(key='geer2021learning', group='A', kind='article', doi='10.1098/rsta.2020.0089',
         pdf='geer2021.pdf', pdf_kind='publisher PDF (downloaded by JXP)',
         sections='6, 7 (framing)', supports='The exact equivalences (4D-Var cost = loss, '
         'adjoint = backpropagation, cycling DA = recurrent network) that let the report '
         'define "ML inside DA", and the list of where learned components can enter DA. '
         'Correction: doi:10.1098/rsta.2022.0004 (2022).'),
    dict(key='cheng2023machine', group='A', kind='article', doi='10.1109/JAS.2023.123537',
         arxiv='2303.10462', pdf='cheng2023.pdf', pdf_kind='arXiv copy',
         sections='7', supports='The systematic survey behind taxonomy categories 2 and 3 '
         '(model-error correction, error-covariance specification, end-to-end learning of '
         'DA, latent-space DA) with 4DVarNet as its ocean exemplar.'),
    dict(key='dheeshjith2025samudra', group='A', kind='article', doi='10.1029/2024GL114318',
         arxiv='2412.03795', pdf='dheeshjith2025.pdf', pdf_kind='arXiv copy',
         sections='7.1', supports='Samudra: full-depth, century-stable global ocean emulator '
         'of GFDL OM4; the clean case of an emulator of a model rather than of a reanalysis.'),
    dict(key='wang2024xihe', group='A', kind='arxiv', arxiv='2402.02995', flags={'preprint'},
         pdf='wang2024.pdf', pdf_kind='arXiv v4',
         sections='7.1', supports='XiHe: the first 1/12 degree data-driven global ocean '
         'forecast model; the GLORYS12-trained family. No journal version found in Crossref '
         'on ' + TODAY + '.'),
    dict(key='cui2025forecasting', group='A', kind='article', doi='10.1038/s41467-025-57389-2',
         pdf='cui2025.pdf', pdf_kind='publisher PDF',
         sections='7.1', supports='WenHai: bulk-formula air-sea fluxes inside the network, '
         'tendency output to preserve mesoscale variance, and the fairest comparison so far '
         'with an operational system (same initial condition and forcing as GLO12v4).'),
    dict(key='elaouni2025glonet', group='A', kind='article', doi='10.1029/2025JH000686',
         arxiv='2412.05454', pdf='elaouni2025.pdf', pdf_kind='arXiv copy',
         sections='7.1', supports='GLONET: an operational center\'s own emulator (Fourier '
         'neural operator plus CNN, 1/4 degree from GLORYS12) with validation metrics beyond '
         'point-wise RMSE; the pre-operational case.'),
    # ---- B. Classical methods and the primer --------------------------------------
    dict(key='evensen2003ensemble', group='B', kind='article', doi='10.1007/s10236-003-0036-9',
         sections='2, 3', supports='The standard reference for the ensemble Kalman gain and '
         'the sampling-error argument behind localization and inflation.'),
    dict(key='bannister2017review', group='B', kind='article', doi='10.1002/qj.2982',
         sections='2, 3', supports='Operational variational and ensemble-variational hybrids '
         '(EnVar, 4DEnVar) in one place, with the notation the primer adopts.'),
    dict(key='edwards2015regional', group='B', kind='article', doi='10.1146/annurev-marine-010814-015821',
         sections='3, 5', supports='The review of regional and coastal DA: open boundaries, '
         'forcing errors, 4D-Var in ROMS and MITgcm, ensemble methods on shelves; written by '
         'the UCSC and Scripps groups the report describes.'),
    dict(key='stammer2016ocean', group='B', kind='article', doi='10.1146/annurev-marine-122414-034113',
         sections='3, 4', supports='The reanalysis and state-estimation side of the split: '
         'sequential reanalyses versus long-window adjoint smoothers (ECCO), what each is for '
         'and why they disagree.'),
    # ---- C. Global systems ----------------------------------------------------------
    dict(key='zuo2019ecmwf', group='C', kind='article', doi='10.5194/os-15-779-2019',
         sections='4', supports='ORAS5/OCEAN5: 3D-Var FGAT with a five-member ensemble, bias '
         'correction and the assimilated observations; the ECMWF row of the systems table.'),
    dict(key='lellouche2018recent', group='C', kind='article', doi='10.5194/os-14-1093-2018',
         sections='4', supports='The operational forecast side of Mercator: the SEEK-derived '
         'reduced-order Kalman filter, 7-day cycle, the GLO12 baseline WenHai and GLONET are '
         'compared against.'),
    dict(key='lellouche2021copernicus', group='C', kind='article', doi='10.3389/feart.2021.698876',
         swap_names=True,
         sections='4, 7.1', supports='GLORYS12, the reanalysis XiHe, WenHai and GLONET are '
         'trained on: its observing inputs, known deficiencies, and its nature as a DA product '
         '(the circularity caveat). The Crossref record holds given and family names reversed; '
         'they are swapped back here.'),
    dict(key='cummings2013variational', group='C', kind='incollection', doi='10.1007/978-3-642-35088-7_13',
         sections='4', supports='NCODA, the 3D-Var used with HYCOM in the U.S. Navy global '
         'system and, as RTOFS\'s parent, at NCEP; source for the Navy row of the table.'),
    dict(key='forget2015ecco', group='C', kind='article', doi='10.5194/gmd-8-3071-2015',
         sections='4', supports='ECCO version 4 as the long-window adjoint smoother; the brief '
         'names ECCO for boundary conditions and the Scripps state estimates use the same '
         'machinery.'),
    dict(key='martin2015status', group='C', kind='article', doi='10.1080/1755876X.2015.1022055',
         sections='4, 5 (table)', supports='The GODAE OceanView intercomparison of operational '
         'systems (Mercator, FOAM, Bluelink, GIOPS, HYCOM/NCODA, RTOFS and others) in one '
         'table; the source for the Bluelink and Copernicus comparator rows (DA33b).'),
    dict(key='rtofs2026ncep', group='C', kind='grey', flags={'grey'},
         url='https://www.nco.ncep.noaa.gov/pmb/products/rtofs/',
         author='{NOAA/NCEP Central Operations}',
         title='{NCEP} Data Products: {RTOFS} (Global Real-Time Ocean Forecast System)',
         year='2026', sections='4 (table)',
         supports='Current description of Global RTOFS (1/12 degree HYCOM, 8-day forecasts). '
         'The older site polar.ncep.noaa.gov/global/ returned HTTP 404 on 2026-09-22.'),
    dict(key='soca2026jcsda', group='C', kind='grey', flags={'grey'},
         url='https://github.com/JCSDA/soca',
         url2='https://jcsda-jedi-docs.readthedocs-hosted.com/en/latest/',
         author='{Joint Center for Satellite Data Assimilation (JCSDA)}',
         title='{SOCA}: Sea-ice, Ocean and Coupled Assimilation ({JEDI} marine data assimilation)',
         year='2026', sections='4 (table), 5 (HAFS)',
         supports='The JEDI-based marine DA (3D-Var FGAT, hybrid 3DEnVar, LETKF) planned for '
         'first operational use in GFSv17/GEFSv13 and used in the HAFS glider experiments of '
         'Liu et al. (2023). No peer-reviewed system paper exists (DA35); the table row '
         'cites this repository and Liu et al. (2023).'),
    # ---- D. Regional and coastal systems -------------------------------------------
    dict(key='moore2011roms', group='D', kind='article', doi='10.1016/j.pocean.2011.05.004',
         sections='5 (UCSC ROMS)', supports='The formulation of ROMS 4D-Var (primal and dual, '
         'strong and weak constraint) that assimilates CUGN. This is Part I of the trilogy '
         '(the Crossref and OpenAlex titles omit the printed "Part I" subtitle); Parts II '
         '(doi:10.1016/j.pocean.2011.05.003) and III (doi:10.1016/j.pocean.2011.05.005) are '
         'named in the text but not separate entries (DA33a).'),
    dict(key='neveu2016historical', group='D', kind='article', doi='10.1016/j.ocemod.2015.11.012',
         sections='5 (UCSC ROMS)', supports='The 31-year California Current ROMS 4D-Var '
         'reanalysis, its observation streams (gliders included) and diagnostics; the '
         'reanalysis side of the regional split.'),
    dict(key='todd2011poleward', group='D', kind='article', doi='10.1029/2010JC006536',
         sections='5 (Scripps state estimate), 9', supports='CUGN Line 90 and 80 data in a '
         'MITgcm adjoint California Current state estimate; the brief cites it as '
         '[demonstrated] glider assimilation.'),
    dict(key='zaba2018annual', group='D', kind='article', doi='10.1175/JPO-D-18-0037.1',
         sections='5, 9', supports='The Scripps California Current state estimate evaluated '
         'against CUGN: what a glider network does and does not constrain.'),
    dict(key='levin2020observation', group='D', kind='article', doi='10.1016/j.ocemod.2020.101721',
         sections='5 (Rutgers doppio), 9', supports='The doppio ROMS 4D-Var system and '
         'quantified observation impacts by platform, gliders included; Part II '
         '(doi:10.1016/j.ocemod.2020.101731) is the companion.'),
    dict(key='wcofs2026coops', group='D', kind='grey', flags={'grey'},
         url='https://tidesandcurrents.noaa.gov/ofs/wcofs/wcofs.html',
         author='{NOAA Center for Operational Oceanographic Products and Services}',
         title='West Coast Operational Forecast System ({WCOFS})',
         year='2026', sections='5 (NOS OFS)',
         supports='Operational description of WCOFS (ROMS-based, U.S. West Coast); the DA '
         'configuration is taken from the page or from Kurapov et al. (2016, Ocean Dyn., '
         'doi:10.1007/s10236-016-1013-4) if the page is silent.'),
    dict(key='kim2024ocean', group='D', kind='article', doi='10.3389/feart.2024.1399409',
         sections='5 (hurricane models)', supports='The ocean component of HAFSv1 (HYCOM, '
         'operational 2023), initialized from RTOFS and evaluated against glider, Argo and '
         'buoy observations.'),
    dict(key='liu2023impact', group='D', kind='article', doi='10.1175/WAF-D-22-0014.1',
         flags={'optional'}, sections='5, 9', supports='Glider assimilation with JEDI/SOCA '
         'into MOM6 coupled to HAFS for Hurricane Isaias (2020); the barrier-layer and '
         'intensity result. Optional: Dong et al. (2017) carries the same point for HWRF-HYCOM.'),
    dict(key='dong2017impact', group='D', kind='article', doi='10.1175/WAF-D-16-0182.1',
         sections='5, 9', supports='The IOOS hurricane-glider result the brief relies on: '
         'glider T/S improved the upper-ocean initial state and barrier layer in HWRF-HYCOM '
         'for Hurricane Gonzalo (2014), with a localized footprint.'),
    # ---- E. Glider-specific DA ---------------------------------------------------------
    dict(key='oke2008representation', group='E', kind='article', doi='10.1175/2007JTECHO558.1',
         sections='9', supports='Definition and estimation of representation '
         '(representativeness) error, the dominant term in R for a glider profile in a '
         'several-km grid.'),
    dict(key='shulman2009impact', group='E', kind='article', doi='10.1016/j.dsr2.2008.08.003',
         sections='9', supports='An early U.S. West Coast glider assimilation study '
         '(NCOM/NCODA, Monterey Bay); the profile-versus-model impact used in the '
         'profile-vs-binned discussion.'),
    dict(key='rudnick2016ocean', group='E', kind='article', doi='10.1146/annurev-marine-122414-033913',
         sections='9', supports='Section 7 of the review covers gliders in assimilating models '
         'and depth-average velocity as an absolutely referenced observation; digested in '
         'context/sources/rudnick2016.md.'),
    dict(key='halliwell2017north', group='E', kind='article', doi='10.1080/1755876X.2017.1322770',
         flags={'optional'}, sections='9', supports='The fraternal-twin OSSE methodology '
         '(HYCOM) used to value hurricane-season ocean observations; the template for OSSE '
         'claims in the glider section.'),
    dict(key='moore2018reduced', group='E', kind='article', doi='10.1002/2017JC013172',
         flags={'optional'}, sections='7.4, 9', supports='Adjoint-based observing-system '
         'analysis of the California Current array (gliders, HF radar, satellites) in ROMS '
         '4D-Var; the classical counterpart of ML adaptive sampling and the method behind '
         'observing-system design in the brief.'),
    # ---- F. AI in NWP ----------------------------------------------------------------------
    dict(key='bi2023accurate', group='F', kind='article', doi='10.1038/s41586-023-06185-3',
         pdf='bi2023.pdf', pdf_kind='publisher PDF',
         sections='6 (emulators)', supports='Pangu-Weather, the first ML medium-range model to '
         'beat the operational IFS on reanalysis-based scores; the opening milestone of the '
         'NWP track in Fig. 2.'),
    dict(key='lam2023learning', group='F', kind='article', doi='10.1126/science.adi2336',
         arxiv='2212.12794', pdf='lam2023.pdf', pdf_kind='arXiv copy',
         sections='6 (emulators)', supports='GraphCast, the graph-neural-network emulator '
         'trained on ERA5; the reference point for what "beats the operational system" means '
         'when the targets are reanalysis fields.'),
    dict(key='lang2024aifs', group='F', kind='arxiv', arxiv='2406.01465', flags={'preprint'},
         pdf='lang2024.pdf', pdf_kind='arXiv',
         sections='6 (emulators)', supports='AIFS, the ECMWF data-driven forecasting system '
         'that became operational in February 2025; the operational exemplar.'),
    dict(key='ecmwf2025aifs', group='F', kind='grey', flags={'grey', 'optional'},
         url='https://www.ecmwf.int/en/about/media-centre/news/2025/ecmwfs-ai-forecasts-become-operational',
         author='{European Centre for Medium-Range Weather Forecasts}',
         title="{ECMWF}'s {AI} forecasts become operational",
         year='2025', month='feb', day='25', sections='6, Fig. 2',
         supports='The date on which AIFS Single became operational (25 February 2025), the '
         'first ML forecast model run operationally by a major center; a timeline milestone. '
         'Optional: needed only for the milestone date.'),
    dict(key='price2024probabilistic', group='F', kind='article', doi='10.1038/s41586-024-08252-9',
         pdf='price2024.pdf', pdf_kind='publisher PDF',
         sections='6 (emulators, probabilistic)', supports='GenCast, the diffusion-based '
         'probabilistic emulator; the ensemble step of the NWP track.'),
    dict(key='bonavita2020machine', group='F', kind='article', doi='10.1029/2020MS002232',
         pdf='bonavita2020.pdf', pdf_kind='publisher PDF (downloaded by JXP 2026-09-23, DA40)',
         sections='6 (learned DA), 7.2', supports='Learned model-error correction at ECMWF: '
         'an ANN trained on operational analysis increments predicts model-error tendencies '
         'that are then used inside strong- and weak-constraint 4D-Var; the pattern Section '
         '7.2 looks for in the ocean.'),
    dict(key='hatfield2021building', group='F', kind='article', doi='10.1029/2021MS002521',
         flags={'optional'}, pdf='hatfield2021.pdf', pdf_kind='publisher PDF via Zenodo',
         sections='6 (learned DA), 7.2', supports='Neural tangent-linear and adjoint models of '
         'a parametrization for use inside 4D-Var; the adjoint-surrogate idea.'),
    dict(key='xu2025fuxida', group='F', kind='article', doi='10.1038/s41612-025-01039-3',
         arxiv='2404.08522', pdf='xu2025.pdf', pdf_kind='publisher PDF',
         sections='6 (learned assimilation)', supports='FuXi-DA: learned assimilation of '
         'satellite radiances into an ML forecast model; placed in category 3 (DA36a).'),
    dict(key='allen2025endtoend', group='F', kind='article', doi='10.1038/s41586-025-08897-0',
         pdf='allen2025.pdf', pdf_kind='publisher PDF',
         sections='6 (end-to-end)', supports='Aardvark Weather: end-to-end observation-to-'
         'forecast prediction; the first end-to-end exemplar.'),
    dict(key='alexe2024graphdop', group='F', kind='arxiv', arxiv='2412.15687',
         flags={'preprint', 'optional'}, pdf='alexe2024.pdf', pdf_kind='arXiv',
         sections='6 (end-to-end)', supports='GraphDOP: ECMWF forecasts learnt and initialised '
         'from observations only, with no reanalysis inputs; the second end-to-end exemplar.'),
    dict(key='manshausen2025generative', group='F', kind='article', doi='10.1029/2024MS004505',
         arxiv='2406.16947', pdf='manshausen2025.pdf', pdf_kind='arXiv copy',
         sections='6 (generative DA)', supports='Score-based generative assimilation of sparse '
         'weather stations at km scale, verified on withheld stations; the generative-DA '
         'exemplar.'),
    # ---- G. AI in ocean DA ---------------------------------------------------------------------
    dict(key='yuan2026samudra2', group='G', kind='arxiv', arxiv='2606.02610',
         flags={'preprint', 'optional'}, pdf='yuan2026.pdf', pdf_kind='arXiv',
         sections='7.1', supports='Samudra 2: ocean emulators at 1, 1/2 and 1/4 degree; the '
         'most recent entry on the ocean track. Optional (recency).'),
    dict(key='chattopadhyay2024oceannet', group='G', kind='article', doi='10.1038/s41598-024-72145-0',
         arxiv='2310.00813', pdf='chattopadhyay2024.pdf', pdf_kind='publisher PDF',
         sections='7.1 (regional emulator)', supports='OceanNet: a neural-operator regional '
         'emulator of northwest Atlantic SSH (Gulf Stream, Loop Current); the regional case '
         'the ocean track otherwise lacks.'),
    dict(key='gregory2023deep', group='G', kind='article', doi='10.1029/2023MS003757',
         arxiv='2304.03832', pdf='gregory2023.pdf', pdf_kind='arXiv copy',
         sections='7.2', supports='Learned systematic model error from DA increments in the '
         'GFDL SPEAR ice-ocean system; the nearest ocean-side analogue of Bonavita and '
         'Laloyaux (2020).'),
    dict(key='zanna2020data', group='G', kind='article', doi='10.1029/2020GL088376',
         flags={'optional'}, pdf='zanna2020.pdf',
         pdf_kind='publisher PDF (not open access; downloaded by JXP 2026-09-23, DA40)',
         sections='7.2 (boundary case)', supports='Data-driven '
         'discovery of a mesoscale eddy closure; the one learned-parameterization paper kept '
         'as a one-sentence boundary case (changes the model, not the assimilation; DA36c).'),
    dict(key='fablet2021learning', group='G', kind='article', doi='10.1029/2021MS002572',
         arxiv='2007.12941', pdf='fablet2021_james.pdf',
         pdf_kind='publisher PDF, downloaded by JXP 2026-09-23 (DA40); fablet2021.pdf is the '
         '2020 arXiv v1 under the preprint title',
         sections='7.3', supports='4DVarNet: joint learning of a variational prior and its '
         'solver on Lorenz systems; the idealized origin of the end-to-end ocean mappers.'),
    dict(key='beauchamp2023fourdvarnet', group='G', kind='article', doi='10.5194/gmd-16-2119-2023',
         arxiv='2211.05904', pdf='beauchamp2023.pdf', pdf_kind='publisher PDF',
         sections='7.3', supports='4DVarNet-SSH on the NATL60 SSH-mapping data challenge; the '
         'OSSE half of the "what verified means" pair.'),
    dict(key='martin2023synthesizing', group='G', kind='article', doi='10.1029/2022MS003589',
         flags={'optional'}, pdf='martin2023.pdf', pdf_kind='publisher PDF via EarthArXiv',
         sections='7.3', supports='Deep-learning SSH interpolation from real altimetry and SST, '
         'verified on withheld altimeter tracks; the OSE half of the pair. Optional (one of two '
         'SSH-mapping exemplars).'),
    dict(key='oceandatachallenges2026', group='G', kind='grey', flags={'grey'},
         url='https://github.com/ocean-data-challenges/2020a_SSH_mapping_NATL60',
         author='{ocean-data-challenges consortium}',
         title='2020a {SSH} mapping {NATL60} data challenge (and the 2021a {OSE} challenge)',
         year='2026', sections='7.3',
         supports='The shared benchmark on which 4DVarNet and the other neural mappers are '
         'scored; defines the OSSE (NATL60) versus OSE (real data) verification split.'),
    dict(key='sugiura2020machine', group='G', kind='article', doi='10.1029/2019EA001019',
         arxiv='1907.00500', pdf='sugiura2020.pdf', pdf_kind='arXiv copy',
         sections='7.4', supports='ML quality control of Argo profiles with the signature '
         'method; the QC exemplar of category 4.'),
    # ---- H. BGC ------------------------------------------------------------------------------------
    dict(key='fennel2019advancing', group='H', kind='article', doi='10.3389/fmars.2019.00089',
         sections='8', supports='The OceanObs\'19 statement of BGC DA status: what is '
         'assimilated (ocean colour, BGC-Argo), physics-BGC coupling problems, '
         'non-Gaussianity, the gap to operations.'),
    dict(key='mattern2017data', group='H', kind='article', doi='10.1016/j.ocemod.2016.12.002',
         sections='8', supports='Coupled physical-BGC 4D-Var in the California Current ROMS '
         'with two ecosystem models; shows the model dependence of BGC assimilation.'),
    dict(key='verdy2017data', group='H', kind='article', doi='10.1002/2016JC012650',
         sections='8', supports='B-SOSE: adjoint state estimation with carbon, oxygen and '
         'nutrients constrained by floats and ships; the state-estimation side of BGC DA.'),
    dict(key='carroll2020ecco', group='H', kind='article', doi='10.1029/2019MS001888',
         sections='8', supports='ECCO-Darwin: the Darwin ecosystem model coupled to the ECCO '
         'state estimate; the global BGC state-estimation reference.'),
    dict(key='ford2021assimilating', group='H', kind='article', doi='10.5194/bg-18-509-2021',
         flags={'optional'}, sections='8, 9', supports='A BGC OSSE valuing in situ '
         'chlorophyll, nitrate, oxygen and pH profiles against ocean colour; the template for '
         'asking what glider O2, pH and chlorophyll would add.'),
    dict(key='bittig2018canyonb', group='H', kind='article', doi='10.3389/fmars.2018.00328',
         flags={'optional'}, pdf='bittig2018.pdf', pdf_kind='publisher PDF',
         sections='8, 7.4', supports='CANYON-B: Bayesian neural-network estimation of '
         'nutrients and carbonate variables from T, S and O2, the variables a glider carries; '
         'category 4 (DA36b).'),
    dict(key='gloege2022improved', group='H', kind='article', doi='10.1029/2021MS002620',
         flags={'optional'}, pdf='gloege2022.pdf', pdf_kind='publisher PDF via NOAA IR',
         sections='8, 7.2', supports='ML correction of global-model pCO2 misfit against '
         'observations; a category-2 case on the BGC side.'),
]

# AI papers: taxonomy category, maturity tag, verification note, and the basis of the
# note (full text in hand, or abstract only).  Filled from the PDFs fetched by
# fetch_pdfs.py; "abstract only" marks what could not be read in full.
AI_NOTES = {
    'dheeshjith2025samudra': (1, 'realistic hindcast',
        'against held-out years of the parent model OM4, not against observations; '
        'underestimates forced trends by 20-50%', 'full text'),
    'wang2024xihe': (1, 'realistic hindcast',
        'IV-TT Class 4 against Argo, drifter and along-track altimeter observations for '
        'Jan 2019-Dec 2020, plus GLORYS12 and tropical moorings; trained on GLORYS12. The '
        'data section gives the GLORYS12 span as 1993-2020 while the abstract and '
        'conclusion say "25-year" training data, which ends in 2017 or 2018 and implies the '
        'test years were withheld, but the split is never stated explicitly', 'full text'),
    'cui2025forecasting': (1, 'realistic hindcast bordering on pre-operational',
        'withheld observations (Class 4: Argo T/S, drifter SST and 15 m currents, along-track '
        'SLA), RMSE and neighborhood CRPS; trained on GLORYS12 1993-2018, validated on 2019; '
        'forecasts Apr-Nov 2024 from operational GLO12v4 analyses', 'full text'),
    'elaouni2025glonet': (1, 'pre-operational',
        'IV-TT Class 4 against Argo T/S, drifter and altimeter observations, weekly '
        'initializations, plus GLORYS12 and GLO12; trained on GLORYS12', 'full text'),
    'bi2023accurate': (1, 'realistic hindcast (research system; no operational status stated)',
        'trained on ERA5 1979-2017, validated on 2019, tested on 2018 (and 2020-2021 in '
        'Extended Data); scored against ERA5 only, the reanalysis it was trained on, with '
        'cyclone tracks against IBTrACS; the authors note that it "was trained and tested on '
        'reanalysis data, but real-world forecast systems work on observational data". '
        '5-day Z500 RMSE 296.7 vs 333.7 for operational IFS', 'full text'),
    'lam2023learning': (1, 'realistic hindcast (research system; "should not be regarded as '
        'a replacement for traditional weather forecasting methods")',
        'trained on ERA5 1979-2015, validated 2016-2017, test 2018-2021 explicitly held out; '
        'GraphCast scored against ERA5 and HRES against its own analyses (HRES-fc0); no '
        'verification against stations or radiosondes; better than HRES on 90% of 1380 '
        'targets', 'full text'),
    'lang2024aifs': (1, 'operational (experimental operational mode from October 2023 per the '
        'paper; AIFS Single operational since 25 February 2025 per ecmwf2025aifs)',
        'pre-trained on ERA5 1979-2020, fine-tuned on IFS operational analyses 2019-2020; '
        'scored for 2022 against the operational ECMWF analysis and against radiosonde and '
        'SYNOP observations; the day-1 degradation seen against analyses "is not present in '
        'verification against radiosonde observations"; about 10% better than IFS through '
        'the troposphere; initialised from the IFS 4D-Var analysis', 'full text'),
    'price2024probabilistic': (1, 'realistic hindcast (research system; no operational status stated)',
        'trained on ERA5 1979-2018, tested on 2019 after freezing the model; each model '
        'evaluated against its own best-estimate analysis (GenCast vs ERA5, ENS vs HRES-fc0), '
        'no observations; better CRPS than ENS on 97.2% of 1320 targets; the authors '
        'underscore "the importance ... of traditional NWP-based data assimilation for '
        'providing training and initialization data"', 'full text'),
    'bonavita2020machine': (2, 'realistic hindcast (ANN trained offline, then used inside '
        'cycled 4D-Var at the operational IFS configuration, Cycle 47R1, TCo1279, 16 July-24 '
        'August 2019; the authors call the results preliminary and the hybrid a '
        'proof-of-concept, "not yet fully in place for reliable operational use")',
        'training target is a DA product: operational 12 h analysis increments (A-B) of 2018 '
        'at T21 (about 900 km), with the background column and location/time as predictors; '
        'validated Jan-Feb 2019, tested from 1 April 2019 for 3.5 months, where the best ANN '
        'explains about 14% of the increment variance for mass, 5% for wind and none for '
        'humidity; the two assimilation experiments (NN_SC: ANN forcing in strong-constraint '
        '4D-Var; NN_WC: ANN as first guess of the weak-constraint forcing) are verified '
        'against observations, not against a DA product: mean and standard deviation of '
        'background departures for radiosondes, GPS-RO, conventional winds, AMVs and surface '
        'pressure, and 72 h temperature forecast RMSE against independent GPS-RO retrievals '
        '(Z500 and MSLP against own analysis). They replicate the stratospheric bias '
        'reduction of weak-constraint 4D-Var, extend the correction to the troposphere and '
        'roughly halve surface-pressure biases; most differences are not statistically '
        'significant over the 5-6 week test', 'full text'),
    'hatfield2021building': (2, 'realistic hindcast (IFS 46r1 at TCo399, one parametrization: '
        'non-orographic gravity-wave drag; the network replaces only the linear models, '
        'not the nonlinear scheme)', 'trained on IFS scheme inputs and outputs 2015, '
        'validated 2016, tested 2017; tangent-linear and adjoint consistency tests, then a '
        'cycled 4D-Var run Dec 2018-Feb 2019 with 177 ten-day forecasts scored against each '
        'experiment\'s own analysis (RMSE differences no more than 4%, not significant) and '
        'departures against ATMS and GPSRO observations that are themselves assimilated',
        'full text'),
    'xu2025fuxida': (3, 'realistic hindcast, offline and non-cycled, verified against ERA5 '
        '(a "feasibility" study; all-sky assimilation not yet demonstrated)',
        'assimilates FY-4B AGRI brightness temperatures (channels 8-15, super-obbed to 0.25 '
        'degree) into a background from a FuXi 6 h forecast initialised from ERA5; the '
        'training target is ERA5 and ERA5 is the ground truth for all metrics, no independent '
        'observations; data split per the Methods section: training June 2022-May 2023, '
        'validation June-July 2023, test August-December 2023 (the Results section states the '
        'training span inconsistently as June 2022-June 2024, which would overlap the test '
        'period; the report uses the Methods split, DA43); analysis RMSE 2-4.5% lower than a '
        'bias-corrected background, Z500 forecast error 0.67% lower at day 1', 'full text'),
    'allen2025endtoend': (3, 'realistic hindcast (research prototype; the paper lists the steps '
        'still needed for operational deployment)',
        'encoder and processor pre-trained with ERA5 as target, station decoder trained on '
        'HadISD observations, then end-to-end fine-tuning; 2018 held out as test, 2019 as '
        'validation; gridded fields scored against ERA5 (HRES and GFS baselines at 1.5 '
        'degrees), station forecasts against held-out HadISD observations (station-corrected '
        'HRES and NDFD baselines); no NWP product is used as input at test time, but ERA5 '
        'is the pre-training target, so the observation-only claim holds for deployment, not '
        'for training; uses about 8% of the observations conventional NWP uses', 'full text'),
    'alexe2024graphdop': (3, 'realistic hindcast (ECMWF research system; "not yet close to '
        'matching state-of-the-art NWP performance")',
        'trained on observations 2004-2021 with 2022 for validation, target = the next 12 h '
        'of observations; no reanalysis in training except an ERA5-departure QC step the '
        'authors flag as a partial dependence; verified in observation space (SYNOP 2 m '
        'temperature, AMSU-A and SSMIS brightness temperatures) against operational IFS, and '
        'on a grid against ERA5 for January 2023, ERA5 "employed exclusively for '
        'verification"; 15% better than IFS for 2 m temperature at day 1, mixed at days 3-5, '
        'worse for AMSU-A channels', 'full text'),
    'manshausen2025generative': (3, 'realistic hindcast ("proof of concept, and the first at '
        'km-scale"; 3 km, 128x128 domain around Oklahoma)', 'diffusion prior trained on HRRR '
        'analyses of 10 m wind and precipitation 2018-2021, observations used only at '
        'inference; tested on 2017 ISD stations with 40 assimilated and 10 held out; about 10% '
        'lower RMSE than the HRRR analysis at the held-out stations, but those stations are '
        'part of the METAR data HRRR itself assimilates; ensembles underdispersive',
        'full text'),
    'yuan2026samudra2': (1, 'realistic hindcast (emulator of a model; no DA and no operational '
        'claim)', 'trained on GFDL OM4 output coarse-grained to 1, 1/2 and 1/4 degree, '
        '1975-2013; about 8-year rollouts 2014-2022 scored against the OM4 truth at each '
        'resolution, no observations; upper-ocean temperature R^2 0.56 to 0.87 at 1 degree '
        'versus Samudra, deep-ocean R^2 still negative at all resolutions', 'full text'),
    'chattopadhyay2024oceannet': (1, 'realistic hindcast (emulator of a regional reanalysis; the '
        'authors call it "initial steps" and note real systems run on real-time observations)',
        'trained on a 4 km ROMS-EnKF northwest Atlantic reanalysis 1993-2018 (SSH target, '
        '5-day mean, 90-120 day horizon); tested on 2019-2020 against the same reanalysis, '
        'not observations; matches a ROMS forecast in the Gulf of Mexico and beats it in the '
        'Gulf Stream region on RMSE, correlation and eddy shape', 'full text'),
    'gregory2023deep': (2, 'realistic hindcast, offline feasibility study (GFDL SPEAR ice-ocean '
        'EAKF, 1982-2017)', 'predicts sea-ice concentration increments from model state and '
        'tendencies; 5-fold cross-validation on contiguous chunks plus an untouched 2018-2021 '
        'extension; skill against the DA increments themselves relative to a climatological-'
        'increment benchmark, not against independent observations; daily pattern '
        'correlations 0.62-0.80', 'full text'),
    'zanna2020data': (2, 'idealized (boundary case: a learned sub-grid closure, not a DA '
        'component; idealized MITgcm double-gyre runs, barotropic at 3.75 km and baroclinic '
        'at 7.5 km, coarse-grained to 30 km)',
        'no observations anywhere: RVM equation discovery and a physics-constrained CNN are '
        'fitted to the diagnosed sub-grid eddy forcing of the high-resolution runs (1000 '
        'snapshots, 50% training, 50% validation; R^2 and correlation offline, e.g. '
        'temperature forcing correlation 0.6 with the variance underestimated by about 50%), '
        'then run online in a different 30 km idealized shallow-water model with the forcing '
        'attenuated by trial-and-error factors 0.5-0.7 for stability, and compared with the '
        '3.75 km run on kinetic energy and its spectrum and PDFs', 'full text (skimmed)'),
    'fablet2021learning': (3, 'idealized (Lorenz-63, Lorenz-96)',
        'supervised on simulated true states or unsupervised on the 4D-Var cost; separate '
        'test sequences (2000 for Lorenz-63, 256 for Lorenz-96) scored by reconstruction '
        'error against the simulated truth; e.g. Lorenz-63 error 1.34 versus 3.55 for '
        'gradient descent on the known-ODE 4D-Var cost, Lorenz-96 0.38 versus 1.06; the '
        'conclusion asks whether the findings "generalize to other systems, especially '
        'higher-dimensional ones". Published JAMES version read 2026-09-23: same six authors, '
        'same two experiments and headline numbers as the 2020 arXiv v1 (which carries the '
        'preprint title "End-to-end learning for variational data assimilation models and '
        'solvers"); the published version fills two placeholder cells of Table 1, expands the '
        'related-work section with pointers to the group\'s SSH applications and archives the '
        'code on Zenodo', 'full text (published version)'),
    'beauchamp2023fourdvarnet': (3, 'realistic OSSE (NATL60, 1/60 degree simulation)',
        'trained on NATL60 with pseudo-observations along 2003 nadir tracks and a simulated '
        'SWOT swath; test window Oct-Dec 2012 separate from training; scored against the '
        'simulated truth, not observations; 30-60% lower reconstruction error than the '
        'operational OI, resolved scales 0.83 degree / 8 days versus 1.42 degree / 12 days for '
        'DUACS; application to real altimetry named as future work', 'full text'),
    'martin2023synthesizing': (3, 'realistic hindcast (Gulf Stream Extension, real altimetry '
        'and SST 2010-2020)', 'trained and tested on real observations: 2017 withheld for '
        'testing, CryoSat-2 withheld as ground truth, AOML drifters as an independent set; '
        '17% lower RMSE and 30% smaller resolved scales than DUACS OI, 24-27% lower surface-'
        'current RMSE against drifters', 'full text'),
    'sugiura2020machine': (4, 'realistic, offline method demonstration (82,000 Argo T/S profiles '
        'deeper than 1000 m)', 'target is the JAMSTEC delayed-mode QC flag; 40% of profiles '
        '(randomly chosen, split by float not stated) for training, 60% for cross-validation; '
        'skill against the human delayed-mode flags, with ROC curves only; beats PCA baselines '
        'and the plotted real-time QC operating points; accepts about 60% of bad profiles at '
        'the cutoff that misflags no good ones', 'full text'),
    'bittig2018canyonb': (4, 'realistic, released mapping method with code (a "transfer '
        'function between components of the ocean observing system", not a DA component)',
        'Bayesian neural networks trained on GLODAPv2 bottle data (521 cruises, 1972-2013) '
        'with 20% set aside; validated against 19 post-GLODAPv2 GO-SHIP cruises 2012-2017 as '
        'a completely independent set, plus Argo pH and pCO2 floats and underway pCO2; RMSE '
        'nitrate 0.68, phosphate 0.051, silicate 2.3, AT 6.3, CT 7.1 umol/kg, pH 0.013, pCO2 '
        '20 uatm on the combined validation data', 'full text'),
    'gloege2022improved': (2, 'realistic hindcast, released observation-based product (LDEO-HPD, '
        '1982-2018)', 'XGBoost learns the SOCAT-minus-model pCO2 misfit for nine global '
        'biogeochemical models and adds it back; seven whole years withheld for testing, plus '
        'fully independent non-SOCAT data (LDEO with SOCAT removed, GLODAPv2, BATS, HOT); '
        'RMSE against GLODAP in the 2010s 15.4 versus 15.7-17.7 for other products',
        'full text'),
}


# ----------------------------------------------------------------------------------
# Fetching and checking
# ----------------------------------------------------------------------------------
def cached_get(url, name, use_cache=True):
    """ GET a URL as text, caching the body under CACHE/name. Generated by JXP and Claude """
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, re.sub(r'[^A-Za-z0-9._-]', '_', name))
    if use_cache and os.path.exists(path):
        with open(path) as fh:
            return fh.read()
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as resp:
        body = resp.read().decode('utf-8')
    with open(path, 'w') as fh:
        fh.write(body)
    return body


def crossref(doi, use_cache=True):
    """ Crossref work record for a DOI (the 'message' object). Generated by JXP and Claude """
    body = cached_get('https://api.crossref.org/works/' + urllib.parse.quote(doi, safe=''),
                      'crossref_' + doi, use_cache)
    return json.loads(body)['message']


def arxiv(aid, use_cache=True):
    """ arXiv API record for an ID: dict(title, authors, year, month, primary, updated). Generated by JXP and Claude """
    body = cached_get('https://export.arxiv.org/api/query?id_list=' + aid, 'arxiv_' + aid, use_cache)
    ns = {'a': 'http://www.w3.org/2005/Atom', 'x': 'http://arxiv.org/schemas/atom'}
    entry = ET.fromstring(body).find('a:entry', ns)
    title = ' '.join(entry.find('a:title', ns).text.split())
    authors = [a.find('a:name', ns).text for a in entry.findall('a:author', ns)]
    published = entry.find('a:published', ns).text
    updated = entry.find('a:updated', ns).text
    prim = entry.find('x:primary_category', ns)
    return dict(title=title, authors=authors, year=published[:4], month=int(published[5:7]),
                primary=prim.get('term') if prim is not None else '', updated=updated[:10])


def head_code(url):
    """ HTTP status of `curl -sI url` (first response, no redirect following). Generated by JXP and Claude """
    res = subprocess.run(['curl', '-sI', '-A', UA['User-Agent'], '--max-time', '40', url],
                         capture_output=True, text=True)
    m = re.match(r'HTTP/[\d.]+\s+(\d{3})', res.stdout)
    return int(m.group(1)) if m else None


def head_code_follow(url):
    """ Final HTTP status of `curl -sI -L url`. Generated by JXP and Claude """
    res = subprocess.run(['curl', '-sI', '-L', '-A', UA['User-Agent'], '--max-time', '40', url],
                         capture_output=True, text=True)
    codes = re.findall(r'HTTP/[\d.]+\s+(\d{3})', res.stdout)
    return int(codes[-1]) if codes else None


# ----------------------------------------------------------------------------------
# Formatting
# ----------------------------------------------------------------------------------
def cr_authors(cr, swap=False):
    """ Crossref author list as [(family, given)]; organizations as (name, '').

    swap=True exchanges the two fields, for records in which Crossref holds them
    reversed (lellouche2021copernicus: family='Jean-Michel', given='Lellouche').

    Generated by JXP and Claude
    """
    out = []
    for a in cr.get('author', []):
        if 'family' in a:
            fam, giv = a['family'].strip(), a.get('given', '').strip()
            if swap:
                fam, giv = giv, fam
            out.append((fam.replace('‐', '-'), giv.replace('‐', '-')))
        elif 'name' in a:
            out.append((a['name'].strip(), ''))
    return out


def arxiv_authors(names):
    """ arXiv 'Given Family' strings to [(family, given)]. Generated by JXP and Claude """
    out = []
    for n in names:
        parts = n.split()
        out.append((parts[-1], ' '.join(parts[:-1])) if len(parts) > 1 else (n, ''))
    return out


def initials(given):
    """ 'Andrew M.' -> 'A. M.'; 'Jean-Michel' -> 'J.-M.'. Generated by JXP and Claude """
    out = []
    for tok in given.replace('.', '. ').split():
        if not tok:
            continue
        out.append('-'.join(p[0] + '.' for p in tok.split('-') if p))
    return ' '.join(out)


def md_authors(auth):
    """ 'Family, I., Family, I., and Family, I.' for the Markdown file. Generated by JXP and Claude """
    names = [f'{f}, {initials(g)}' if g else f for f, g in auth]
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f'{names[0]} and {names[1]}'
    return ', '.join(names[:-1]) + ', and ' + names[-1]


def bib_authors(auth):
    """ 'Family, Given and Family, Given' for BibTeX. Generated by JXP and Claude """
    return ' and '.join(f'{f}, {g}' if g else '{' + f + '}' for f, g in auth)


def clean_title(t):
    """ Strip the HTML Crossref leaves in titles, collapse whitespace, normalize hyphens.

    Crossref titles can contain <scp>S</scp> outhern (small caps), CO <sub>2</sub> and
    <i>p</i> CO; these are rejoined into 'Southern', 'CO2' and 'pCO'.

    Generated by JXP and Claude
    """
    t = re.sub(r'<scp>\s*(.*?)\s*</scp>\s*', r'\1', t, flags=re.S)
    t = re.sub(r'\s*<sub>\s*(.*?)\s*</sub>', r'\1', t, flags=re.S)
    t = re.sub(r'\s*<sup>\s*(.*?)\s*</sup>', r'\1', t, flags=re.S)
    t = re.sub(r'<i>\s*(.*?)\s*</i>\s*', r'\1', t, flags=re.S)
    t = re.sub(r'<[^>]+>', '', t)
    return ' '.join(t.replace('‐', '-').replace('‑', '-').split())


def bib_escape(s):
    """ Escape the characters BibTeX treats specially in free text. Generated by JXP and Claude """
    return s.replace('&', r'\&').replace('%', r'\%').replace('_', r'\_').replace('#', r'\#')


def pages_field(cr):
    """ (pages, article_number) from a Crossref record. Generated by JXP and Claude """
    page = cr.get('page', '')
    art = cr.get('article-number', '')
    if page and '-' in page:
        a, b = page.split('-', 1)
        page = f'{a}--{b}'
    return page, art


def cr_year(cr):
    """ Year of first publication (Crossref 'issued'). Generated by JXP and Claude """
    for k in ('issued', 'published-online', 'published-print'):
        dp = cr.get(k, {}).get('date-parts', [[None]])[0]
        if dp and dp[0]:
            return str(dp[0])
    return ''


def status_of(e):
    """ verified | preprint | grey, per the reading-list convention. Generated by JXP and Claude """
    if 'grey' in e.get('flags', set()):
        return 'grey'
    if e['kind'] == 'arxiv':
        return 'preprint'
    return 'verified' if e.get('doi_code') and 300 <= e['doi_code'] < 400 else 'unverified'


def build_entry(e, use_cache):
    """ Attach the fetched metadata and verification results to an entry dict. Generated by JXP and Claude """
    e.setdefault('flags', set())
    if e['kind'] in ('article', 'incollection'):
        cr = crossref(e['doi'], use_cache)
        e['authors'] = cr_authors(cr, swap=e.get('swap_names', False))
        e['title'] = e.get('title_override') or clean_title(cr['title'][0])
        e['crossref_title'] = clean_title(cr['title'][0])
        e['journal'] = clean_title(cr.get('container-title', [''])[0]) if cr.get('container-title') else ''
        e['volume'] = cr.get('volume', '')
        e['issue'] = cr.get('issue', '')
        e['pages'], e['artnum'] = pages_field(cr)
        e['year'] = cr_year(cr)
        e['publisher'] = cr.get('publisher', '')
        e['doi_code'] = head_code('https://doi.org/' + e['doi'])
    if e['kind'] == 'arxiv':
        ax = arxiv(e['arxiv'], use_cache)
        e['authors'] = arxiv_authors(ax['authors'])
        e['title'] = ax['title']
        e['year'] = ax['year']
        e['primary'] = ax['primary']
        e['arxiv_updated'] = ax['updated']
        e['arxiv_doi'] = '10.48550/arXiv.' + e['arxiv']
        e['doi_code'] = head_code('https://doi.org/' + e['arxiv_doi'])
    elif e.get('arxiv'):
        # companion preprint of a journal article: confirm the ID points at the same paper
        ax = arxiv(e['arxiv'], use_cache)
        e['arxiv_title'] = ax['title']
        w_have = set(re.findall(r'[a-z0-9]{3,}', ax['title'].lower()))
        w_want = re.findall(r'[a-z0-9]{3,}', e['title'].lower())
        e['arxiv_match'] = sum(w in w_have for w in w_want) / max(1, len(w_want))
    if e['kind'] == 'grey':
        e['url_code'] = head_code_follow(e['url'])
        if e.get('url2'):
            e['url2_code'] = head_code_follow(e['url2'])
    return e


# ----------------------------------------------------------------------------------
# Writers
# ----------------------------------------------------------------------------------
def bib_record(e):
    """ One BibTeX record as a string. Generated by JXP and Claude """
    f = []
    flags = sorted(e['flags'])
    note = []
    if e['kind'] in ('article', 'incollection'):
        etype = 'article' if e['kind'] == 'article' else 'incollection'
        f.append(('author', bib_authors(e['authors'])))
        f.append(('title', '{' + bib_escape(e['title']) + '}'))
        if e['kind'] == 'article':
            f.append(('journal', bib_escape(e['journal'])))
        else:
            f.append(('booktitle', bib_escape(e['journal'])))
            f.append(('publisher', bib_escape(e['publisher'])))
        if e['volume']:
            f.append(('volume', e['volume']))
        if e['issue']:
            f.append(('number', e['issue']))
        if e['pages']:
            f.append(('pages', e['pages']))
        elif e['artnum']:
            f.append(('pages', e['artnum']))
        f.append(('year', e['year']))
        f.append(('doi', e['doi']))
        f.append(('url', 'https://doi.org/' + e['doi']))
        f.append(('urldate', TODAY))
        if e.get('arxiv'):
            f.append(('eprint', e['arxiv']))
            f.append(('archivePrefix', 'arXiv'))
            note.append('arXiv:' + e['arxiv'])
    elif e['kind'] == 'arxiv':
        etype = 'misc'
        f.append(('author', bib_authors(e['authors'])))
        f.append(('title', '{' + bib_escape(e['title']) + '}'))
        f.append(('year', e['year']))
        f.append(('eprint', e['arxiv']))
        f.append(('archivePrefix', 'arXiv'))
        if e.get('primary'):
            f.append(('primaryClass', e['primary']))
        if e.get('doi_code') and 300 <= e['doi_code'] < 400:
            f.append(('doi', e['arxiv_doi']))
        f.append(('url', 'https://arxiv.org/abs/' + e['arxiv']))
        f.append(('urldate', TODAY))
        note.append(f'arXiv preprint, latest version dated {e["arxiv_updated"]}; no journal '
                    f'version found in Crossref on {TODAY}')
    else:
        etype = 'online'
        f.append(('author', e['author']))   # already braced as a corporate author
        f.append(('title', e['title']))     # capitalization protected inline
        if e.get('month'):
            f.append(('month', e['month']))
        if e.get('day'):
            f.append(('day', e['day']))
        f.append(('year', e['year']))
        f.append(('url', e['url']))
        f.append(('urldate', TODAY))
        note.append(f'Grey literature; URL returned HTTP {e["url_code"]} on {TODAY}')
        if e.get('url2'):
            note.append(f'documentation: {e["url2"]} (HTTP {e.get("url2_code")})')
    if flags:
        f.append(('keywords', ', '.join(flags)))
    if note:
        f.append(('note', bib_escape('. '.join(note)) + '.'))
    width = max(len(k) for k, _ in f)
    body = ',\n'.join(f'  {k:<{width}} = {{{v}}}' for k, v in f)
    return f'@{etype}{{{e["key"]},\n{body}\n}}\n'


def md_record(n, e):
    """ One numbered sources.md entry. Generated by JXP and Claude """
    lines = []
    status = status_of(e)
    if e['kind'] in ('article', 'incollection'):
        end = '' if e['title'].endswith(('?', '!')) else '.'
        cite = f'{md_authors(e["authors"])} ({e["year"]}). "{e["title"]}{end}" *{e["journal"]}*'
        if e['volume']:
            cite += f' {e["volume"]}'
            if e['issue']:
                cite += f'({e["issue"]})'
        if e['pages']:
            cite += f', {e["pages"].replace("--", "-")}'
        elif e['artnum']:
            cite += f', {e["artnum"]}'
        if e['kind'] == 'incollection':
            cite += f' ({e["publisher"]})'
        cite += '.'
        lines.append(f'{n}. {cite}')
        ver = (f'DOI verified, HTTP {e["doi_code"]} on {TODAY}' if status == 'verified'
               else f'DOI returned HTTP {e["doi_code"]} on {TODAY}')
        doi_line = f'DOI: {e["doi"]} ({ver}).'
        if e.get('arxiv'):
            doi_line += f' arXiv:{e["arxiv"]}.'
        lines.append('    ' + doi_line)
    elif e['kind'] == 'arxiv':
        lines.append(f'{n}. {md_authors(e["authors"])} ({e["year"]}). "{e["title"]}." arXiv:{e["arxiv"]}, '
                     f'latest version {e["arxiv_updated"]}.')
        lines.append(f'    **preprint**: no journal version found in Crossref on {TODAY}. '
                     f'https://arxiv.org/abs/{e["arxiv"]}'
                     + (f' (DOI 10.48550/arXiv.{e["arxiv"]} verified, HTTP {e["doi_code"]}).'
                        if e.get('doi_code') and 300 <= e['doi_code'] < 400 else '.'))
    else:
        title = re.sub(r'[{}]', '', e['title'])
        author = re.sub(r'[{}]', '', e['author'])
        lines.append(f'{n}. **{title}** -- {author}, {e["year"]}.')
        lines.append(f'    URL: {e["url"]} (HTTP {e["url_code"]} on {TODAY}).'
                     + (f' Documentation: {e["url2"]} (HTTP {e.get("url2_code")}).' if e.get('url2') else ''))
        lines.append('    **grey**: web page or repository, no DOI.')
    lines.append(f'    Serves: Section(s) {e["sections"]}.')
    lines.append(f'    Supports: {e["supports"]}')
    if e['key'] in AI_NOTES:
        cat, mat, ver, basis = AI_NOTES[e['key']]
        lines.append(f'    AI notes: category {cat}; maturity: {mat}; verification: {ver}. '
                     f'Basis: {basis}.')
    if e.get('pdf'):
        lines.append(f'    In hand: `context/da/{e["pdf"]}` ({e["pdf_kind"]}; gitignored).')
    tags = [status] + (['optional'] if 'optional' in e['flags'] else [])
    lines.append(f'    Status: {", ".join(tags)}. Key: `{e["key"]}`')
    return '\n'.join(lines) + '\n'


def write_outputs(entries):
    """ Write sources.bib and sources.md. Generated by JXP and Claude """
    counts = {}
    for e in entries:
        counts[status_of(e)] = counts.get(status_of(e), 0) + 1
    n_opt = sum('optional' in e['flags'] for e in entries)
    n_ai = sum(e['key'] in AI_NOTES for e in entries)
    n_full = sum(AI_NOTES[e['key']][3].startswith('full text') for e in entries if e['key'] in AI_NOTES)
    n_pdf = sum(bool(e.get('pdf')) for e in entries)
    dates = ', '.join(VERIFIED_ON)

    with open(BIB_PATH, 'w') as fh:
        fh.write('% sources.bib -- bibliography for the DA and AI review (reports/data_assimilation/)\n')
        fh.write(f'% Companion to sources.md (same keys). Generated by scripts/build_bib.py from\n')
        fh.write(f'% Crossref and arXiv metadata; every DOI and URL re-resolved on {TODAY}\n')
        fh.write(f'% (all runs: {dates}); urldate is the date of the last run.\n')
        fh.write('% keywords: preprint = arXiv only; grey = web page or repository; optional = may be cut.\n')
        for gid, gname in GROUPS:
            fh.write('\n% ' + '-' * 70 + f'\n% {gid}. {gname}\n% ' + '-' * 70 + '\n\n')
            for e in entries:
                if e['group'] == gid:
                    fh.write(bib_record(e) + '\n')

    with open(MD_PATH, 'w') as fh:
        fh.write('# Sources for the DA and AI review\n\n')
        fh.write('**Purpose.** Bibliography for `da_ai_review.md` (`reports/data_assimilation/`), the '
                 'review of data assimilation in oceanography and where AI enters it. One entry per '
                 'reference approved from `reading_list.md` (JXP review, DA33-DA44). Every entry gives '
                 'the BibTeX key used in the companion file `sources.bib`; the report cites only keys '
                 'that appear here. Generated by `scripts/build_bib.py`; do not edit by hand.\n\n')
        fh.write(f'**Access date for all entries: {TODAY}.** Every DOI and URL in this file was '
                 f'resolved by `build_bib.py` on each of these dates: {dates}; the date shown on '
                 'each entry and in `urldate` is the last run. The bibliographic fields were '
                 f'refetched from Crossref and the arXiv API on {TODAY} (no cache).\n\n')
        fh.write('Conventions: "DOI verified" means `curl -sI https://doi.org/<doi>` returned a '
                 f'redirect (HTTP 30x) on {TODAY} and the bibliographic fields were taken from the '
                 'Crossref record for that DOI (author lists complete, volume, issue, pages or '
                 'article number). **preprint** marks arXiv-only items whose metadata come from the '
                 'arXiv API and for which no journal version was found in Crossref. **grey** marks '
                 'web pages and repositories with no DOI; their URL and the HTTP code it returned '
                 'today are given. *optional* marks entries the report can be written without. '
                 '"AI notes" give the taxonomy category (1 emulators; 2 ML inside classical DA; 3 ML '
                 'replacing DA; 4 ML around DA), the maturity tag and the verification note, and '
                 'state whether they rest on the full text or on the abstract only. "In hand" names '
                 'the private PDF in `context/da/` (gitignored). `scripts/check_sources.py` '
                 're-verifies every DOI and URL in `sources.bib`.\n\n')
        parts = ', '.join(f'{v} `{k}`' for k, v in sorted(counts.items()))
        fh.write(f'Counts: {len(entries)} entries; {parts}; {n_opt} optional; {n_ai} AI papers with '
                 f'taxonomy notes, {n_full} of them resting on the full text; {n_pdf} with a PDF in '
                 'hand.\n\n---\n')
        n = 0
        for gid, gname in GROUPS:
            fh.write(f'\n## {gid}. {gname}\n\n')
            for e in entries:
                if e['group'] == gid:
                    n += 1
                    fh.write(md_record(n, e) + '\n')
        # check_sources.py --record replaces the text between these markers
        fh.write('\n---\n\n## Last `check_sources.py` run\n\n<!-- check_sources:begin -->\n'
                 'Not yet run on this version of `sources.bib`; run '
                 '`conda run -n ocean14 python reports/data_assimilation/scripts/check_sources.py --record`.\n'
                 '<!-- check_sources:end -->\n')
    return counts, n_opt


def main():
    """ Fetch metadata, verify identifiers, write the two files, print a summary. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-cache', action='store_true', help='ignore cached API responses')
    args = ap.parse_args()
    keys = [e['key'] for e in ENTRIES]
    assert len(keys) == len(set(keys)), 'duplicate keys'
    entries = []
    for e in ENTRIES:
        e = build_entry(dict(e), not args.no_cache)
        entries.append(e)
        flag = ''
        if e['kind'] in ('article', 'incollection') and not (e['doi_code'] and 300 <= e['doi_code'] < 400):
            flag = '  <-- DOI did not redirect'
        if e.get('arxiv_match', 1.0) < 0.6:
            flag += f'  <-- arXiv title mismatch ({e["arxiv_match"]:.2f}: {e.get("arxiv_title")})'
        if e['kind'] == 'grey' and e['url_code'] != 200:
            flag += f'  <-- URL HTTP {e["url_code"]}'
        ident = e.get('doi') or ('arXiv:' + e['arxiv'] if e.get('arxiv') else e.get('url'))
        print(f'{status_of(e):9s} {e.get("doi_code") or e.get("url_code") or "":>4} {e["key"]:28s} '
              f'{ident}  [{len(e.get("authors", []))} authors]{flag}')
    counts, n_opt = write_outputs(entries)
    print(f'\n# {len(entries)} entries written to {BIB_PATH} and {MD_PATH}')
    print('# status counts: ' + ', '.join(f'{k} {v}' for k, v in sorted(counts.items())) + f'; optional {n_opt}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
