""" Check the citations in da_ai_review.md against sources.bib and estimate its length.

Lists every `[@key]` (and `@key` inside a multi-key bracket) cited in the report, reports
the keys that are missing from ../sources.bib (an error: the report may cite only keys
that exist there) and the keys in sources.bib that the report has not cited yet
(informative while the draft is incomplete; an error only at the prompt-8 verification
pass, where every key must be cited at least once).  Also counts the evidential flags the
draft uses ("[abstract only]", "[not read", "[not re-verified]", "(preprint)", "(grey)")
so the verification pass can collect them.

Then estimates the page count per top-level section (## heading) at 500 words per page,
counting words after removing display math ($$...$$), inline math ($...$), Markdown
tables' pipe characters and the citation keys themselves, so that the estimate tracks
prose rather than markup.  Sections whose body is only a bracketed italic placeholder
are marked as such.

Usage (ocean14):
    conda run -n ocean14 python reports/data_assimilation/scripts/check_citations.py [--strict]

--strict exits 1 if any key in sources.bib is uncited (for prompt 8); missing keys always
exit 1.

Generated by JXP and Claude
"""
import argparse
import os
import re
import sys

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORT = os.path.join(REPORT_DIR, 'da_ai_review.md')
BIB = os.path.join(REPORT_DIR, 'sources.bib')
WORDS_PER_PAGE = 500
FLAGS = ['[abstract only]', '[not read', '[not re-verified]', '(preprint)', '(grey)']


def bib_keys(path):
    """ Keys of every @type{key, record in a BibTeX file. Generated by JXP and Claude """
    with open(path) as fh:
        return re.findall(r'^@\w+\{([^,\s]+),', fh.read(), flags=re.M)


def cited_keys(text):
    """ Ordered list of distinct keys cited as [@key] or [@a; @b] in Markdown. Generated by JXP and Claude """
    keys = []
    for bracket in re.findall(r'\[(@[^\]]+)\]', text):
        for key in re.findall(r'@([A-Za-z0-9_:\-]+)', bracket):
            if key not in keys:
                keys.append(key)
    return keys


def prose_words(text):
    """ Word count of Markdown text with math, table pipes and citation keys removed.

    Parameters
    ----------
    text : str, Markdown

    Returns
    -------
    int

    Generated by JXP and Claude
    """
    text = re.sub(r'\$\$.*?\$\$', ' ', text, flags=re.S)   # display math
    text = re.sub(r'\$[^$\n]+\$', ' ', text)               # inline math
    text = re.sub(r'\[@[^\]]+\]', ' ', text)               # citation brackets
    text = text.replace('|', ' ')
    text = re.sub(r'^\s*[-:| ]+\s*$', ' ', text, flags=re.M)  # table rules
    return len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'\-]*", text))


def split_sections(text):
    """ Split the report at top-level '## ' headings; returns [(heading, body)]. Generated by JXP and Claude """
    parts = re.split(r'^## ', text, flags=re.M)
    sections = [('(front matter)', parts[0])]
    for part in parts[1:]:
        heading, _, body = part.partition('\n')
        sections.append((heading.strip(), body))
    return sections


def is_placeholder(body):
    """ True if the section body is only a bracketed italic placeholder (plus sub-headings). Generated by JXP and Claude """
    stripped = re.sub(r'^###.*$', '', body, flags=re.M)
    stripped = re.sub(r'\*\[Placeholder:.*?\]\*', '', stripped, flags=re.S).strip()
    return stripped == '' and 'Placeholder' in body


def main():
    """ Run the citation check and the length estimate; return the exit code. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--strict', action='store_true', help='fail if any sources.bib key is uncited')
    args = ap.parse_args()

    with open(REPORT) as fh:
        text = fh.read()
    keys_bib = bib_keys(BIB)
    keys_cited = cited_keys(text)
    missing = [k for k in keys_cited if k not in keys_bib]
    uncited = [k for k in keys_bib if k not in keys_cited]

    print(f'# check_citations.py: {os.path.relpath(REPORT, REPORT_DIR)} vs {os.path.relpath(BIB, REPORT_DIR)}')
    print(f'{len(keys_bib)} keys in sources.bib; {len(keys_cited)} distinct keys cited in the report')
    print('cited: ' + ' '.join(keys_cited))
    print(f'missing from sources.bib ({len(missing)}): ' + (' '.join(missing) if missing else 'none'))
    print(f'in sources.bib but not yet cited ({len(uncited)}): ' + (' '.join(uncited) if uncited else 'none'))
    print('flags: ' + ', '.join(f'{f} x{text.count(f)}' for f in FLAGS))

    print(f'\n# length estimate at {WORDS_PER_PAGE} words per page; prose excludes math, '
          'citation keys and table rows, which are counted separately')
    total = total_tab = 0
    for heading, body in split_sections(text):
        table_lines = [ln for ln in body.splitlines() if ln.lstrip().startswith('|')]
        prose_lines = [ln for ln in body.splitlines() if not ln.lstrip().startswith('|')]
        words = prose_words('\n'.join(prose_lines))
        tab = prose_words('\n'.join(table_lines))
        total += words
        total_tab += tab
        tag = '  [placeholder]' if is_placeholder(body) else ''
        print(f'{words:6d} words  {words / WORDS_PER_PAGE:5.2f} pp  (+{tab:4d} table words)  {heading}{tag}')
    print(f'{total:6d} words  {total / WORDS_PER_PAGE:5.2f} pp  (+{total_tab:4d} table words, '
          f'{total_tab / WORDS_PER_PAGE:.2f} pp)  TOTAL')

    if missing:
        return 1
    if args.strict and uncited:
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
