""" Re-verify every DOI and URL in sources.bib before the report is delivered.

Parses ../sources.bib (no external parser needed), then:

- every `doi` field is resolved with `curl -sI https://doi.org/<doi>`; a 30x redirect is
  the pass condition (doi.org never returns 200 for a valid DOI), anything else fails;
- every `url` field that is not a doi.org mirror of the DOI is fetched with
  `curl -sI -L`; a final 200 or 30x passes; a 403 is reported separately as "blocked,
  not broken" (some publisher and agency hosts refuse scripted requests while serving
  the page to a browser, the El Nino 2026 convention); anything else fails;
- unless --no-epmc is given, each DOI is looked up in Europe PMC
  (https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=DOI:<doi>) and the
  isOpenAccess flag and PMCID are printed when the record exists.  This is informative
  only and never fails the run.

Prints one line per check, a summary, and the list of failures; exits 1 if any DOI or
URL fails (403s do not count as failures).  With --record the summary lines are written
into ../sources.md between the `<!-- check_sources:begin/end -->` markers that
build_bib.py leaves there, so the bibliography carries the date and result of its last
check.

Usage (ocean14):
    conda run -n ocean14 python reports/data_assimilation/scripts/check_sources.py [--no-epmc] [--record] [--bib path]

Generated by JXP and Claude
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys
import urllib.parse
import urllib.request

REPORT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_BIB = os.path.join(REPORT_DIR, 'sources.bib')
UA = 'Mozilla/5.0 (compatible; BOONUS-DA-review source check; mailto:jxp@ucsc.edu)'
TIMEOUT = '40'
EPMC = 'https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=DOI:%s&format=json&resultType=lite'


def parse_bib(path):
    """ Minimal BibTeX reader: list of dicts with key, type and the fields we need.

    Handles `field = {value}` and `field = "value"` on one line, which is how
    build_bib.py writes the file.  Nested braces inside a value are tolerated.

    Parameters
    ----------
    path : str

    Returns
    -------
    list of dict(key, type, fields)

    Generated by JXP and Claude
    """
    with open(path) as fh:
        text = fh.read()
    entries = []
    for m in re.finditer(r'@(\w+)\{([^,\s]+),(.*?)\n\}', text, flags=re.S):
        etype, key, body = m.group(1), m.group(2), m.group(3)
        fields = {}
        for fm in re.finditer(r'^\s*(\w+)\s*=\s*(\{(?:[^{}]|\{[^{}]*\})*\}|"[^"]*")\s*,?\s*$', body, flags=re.M):
            fields[fm.group(1).lower()] = fm.group(2)[1:-1]
        entries.append(dict(key=key, type=etype, fields=fields))
    return entries


def curl_codes(url, follow=False):
    """ HTTP status codes returned by `curl -sI [-L] url`, in order (empty on failure). Generated by JXP and Claude """
    cmd = ['curl', '-sI', '-A', UA, '--max-time', TIMEOUT] + (['-L'] if follow else []) + [url]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=90).stdout
    except subprocess.TimeoutExpired:
        return []
    return [int(c) for c in re.findall(r'HTTP/[\d.]+\s+(\d{3})', out)]


def check_doi(doi):
    """ ('ok'|'FAIL', code) for a DOI: pass on a 30x from doi.org. Generated by JXP and Claude """
    codes = curl_codes('https://doi.org/' + doi)
    code = codes[0] if codes else None
    return ('ok' if code and 300 <= code < 400 else 'FAIL'), code


def check_url(url):
    """ ('ok'|'blocked'|'FAIL', final code) for a URL following redirects. Generated by JXP and Claude """
    codes = curl_codes(url, follow=True)
    code = codes[-1] if codes else None
    if code and 200 <= code < 400:
        return 'ok', code
    if code == 403:
        return 'blocked', code
    return 'FAIL', code


def epmc_status(doi):
    """ (isOpenAccess, pmcid) from Europe PMC, or (None, None) when not indexed. Generated by JXP and Claude """
    try:
        req = urllib.request.Request(EPMC % urllib.parse.quote(doi, safe=''), headers={'User-Agent': UA})
        with urllib.request.urlopen(req, timeout=40) as resp:
            res = json.load(resp).get('resultList', {}).get('result', [])
    except Exception:
        return None, None
    if not res:
        return None, None
    return res[0].get('isOpenAccess'), res[0].get('pmcid')


def main():
    """ Check every DOI and URL; print summary; exit 1 on any hard failure. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--bib', default=DEFAULT_BIB)
    ap.add_argument('--no-epmc', action='store_true', help='skip the Europe PMC open-access lookup')
    ap.add_argument('--record', action='store_true', help='write the summary into sources.md')
    args = ap.parse_args()
    entries = parse_bib(args.bib)
    today = datetime.date.today().isoformat()
    print(f'# check_sources.py: {len(entries)} entries in {args.bib}, checked {today}')
    n_doi = n_url = 0
    failures, blocked, oa_yes, oa_no = [], [], [], []
    for e in entries:
        f = e['fields']
        doi = f.get('doi')
        if doi:
            n_doi += 1
            status, code = check_doi(doi)
            line = f'{status:7s} {code or "---":>4} doi  {e["key"]:28s} {doi}'
            if not args.no_epmc and not doi.startswith('10.48550/'):
                oa, pmcid = epmc_status(doi)
                if oa is not None:
                    line += f'   [EuropePMC isOpenAccess={oa}' + (f' {pmcid}' if pmcid else '') + ']'
                    (oa_yes if oa == 'Y' else oa_no).append(e['key'])
            print(line)
            if status == 'FAIL':
                failures.append((e['key'], 'doi', doi, code))
        url = f.get('url')
        if url and not (doi and url.lower().startswith('https://doi.org/')):
            n_url += 1
            status, code = check_url(url)
            print(f'{status:7s} {code or "---":>4} url  {e["key"]:28s} {url}')
            if status == 'FAIL':
                failures.append((e['key'], 'url', url, code))
            elif status == 'blocked':
                blocked.append((e['key'], url))
    summary = [f'{n_doi} DOIs and {n_url} URLs checked on {today}; {len(failures)} failed; '
               f'{len(blocked)} blocked (403, not counted as broken).']
    if not args.no_epmc:
        summary.append(f'Europe PMC: {len(oa_yes)} indexed open access, {len(oa_no)} indexed not open '
                       f'access ({", ".join(oa_no)}), {n_doi - len(oa_yes) - len(oa_no)} not indexed '
                       f'(most earth-science journals are not).')
    for key, url in blocked:
        summary.append(f'Blocked, not broken: `{key}` {url}')
    for key, kind, ident, code in failures:
        summary.append(f'FAILED: `{key}` {kind} {ident} HTTP {code}')
    if not failures:
        summary.append('All DOIs and URLs resolve.')
    print()
    for line in summary:
        print('# ' + line)
    if args.record:
        record(os.path.join(os.path.dirname(args.bib), 'sources.md'), summary)
    return 1 if failures else 0


def record(md_path, summary):
    """ Replace the text between the check_sources markers in sources.md with the summary. Generated by JXP and Claude """
    if not os.path.exists(md_path):
        print(f'# --record: {md_path} not found')
        return
    with open(md_path) as fh:
        md = fh.read()
    begin, end = '<!-- check_sources:begin -->', '<!-- check_sources:end -->'
    if begin not in md or end not in md:
        print(f'# --record: markers not found in {md_path}')
        return
    head, rest = md.split(begin, 1)
    _, tail = rest.split(end, 1)
    body = '\n'.join(f'- {line}' for line in summary)
    with open(md_path, 'w') as fh:
        fh.write(f'{head}{begin}\nOutput of `scripts/check_sources.py --record`:\n\n{body}\n{end}{tail}')
    print(f'# --record: summary written to {md_path}')


if __name__ == '__main__':
    sys.exit(main())
