""" Fetch the open-access PDFs wanted for the DA and AI review into context/da/.

The list below is the set of non-anchor AI papers in reading_list.md (DA37) that have
an open-access copy reachable by a scripted fetch: publisher PDFs where the host
answers curl (Nature family, Frontiers, Copernicus), arXiv or EarthArXiv copies where
the publisher host returns 403 (AGU/Wiley), and repository copies (Zenodo, NOAA IR).
Papers with no such copy are not in the list; they are reported to JXP in Q&A instead.

Every download is checked twice: `file` must call it a PDF, and the text of its first
two pages (pdftotext) must contain most of the words of the expected title.  Files
that fail either check are deleted and reported.  Existing files are not re-fetched
unless --force is given.  The PDFs are gitignored (context/**/*.pdf).

Usage (ocean14):
    conda run -n ocean14 python reports/data_assimilation/scripts/fetch_pdfs.py [--force] [--only key,key]

Generated by JXP and Claude
"""
import argparse
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
DEST = os.path.join(REPO, 'context', 'da')
UA = 'Mozilla/5.0 (BOONUS report fetch; mailto:jxp@ucsc.edu)'

# (file name, reading-list key, URL, expected title, what the copy is)
PDFS = [
    # ---- non-AI system and BGC papers, open access, added for the Draft (prompt #4, DA44)
    ('zuo2019.pdf', 'zuo2019ecmwf',
     'https://os.copernicus.org/articles/15/779/2019/os-15-779-2019.pdf',
     'The ECMWF operational ensemble reanalysis-analysis system for ocean and sea ice: a description of the system and assessment',
     'publisher PDF (Copernicus, CC BY 4.0)'),
    ('lellouche2018.pdf', 'lellouche2018recent',
     'https://os.copernicus.org/articles/14/1093/2018/os-14-1093-2018.pdf',
     'Recent updates to the Copernicus Marine Service global ocean monitoring and forecasting real-time 1/12 high-resolution system',
     'publisher PDF (Copernicus, CC BY 4.0)'),
    ('lellouche2021.pdf', 'lellouche2021copernicus',
     'https://www.frontiersin.org/articles/10.3389/feart.2021.698876/pdf',
     'The Copernicus Global 1/12 Oceanic and Sea Ice GLORYS12 Reanalysis',
     'publisher PDF (Frontiers, CC BY 4.0)'),
    ('forget2015.pdf', 'forget2015ecco',
     'https://gmd.copernicus.org/articles/8/3071/2015/gmd-8-3071-2015.pdf',
     'ECCO version 4: an integrated framework for non-linear inverse modeling and global ocean state estimation',
     'publisher PDF (Copernicus, CC BY 3.0)'),
    ('kim2024.pdf', 'kim2024ocean',
     'https://www.frontiersin.org/articles/10.3389/feart.2024.1399409/pdf',
     'Ocean component of the first operational version of Hurricane Analysis and Forecast System: Evaluation of HYbrid Coordinate Ocean Model and hurricane feedback forecasts',
     'publisher PDF (Frontiers, CC BY 4.0)'),
    ('fennel2019.pdf', 'fennel2019advancing',
     'https://www.frontiersin.org/articles/10.3389/fmars.2019.00089/pdf',
     'Advancing Marine Biogeochemical and Ecosystem Reanalyses and Forecasts as Tools for Monitoring and Managing Ecosystem Health',
     'publisher PDF (Frontiers, CC BY 4.0)'),
    ('ford2021.pdf', 'ford2021assimilating',
     'https://bg.copernicus.org/articles/18/509/2021/bg-18-509-2021.pdf',
     'Assimilating synthetic Biogeochemical-Argo and ocean colour observations into a global ocean model to inform observing system design',
     'publisher PDF (Copernicus, CC BY 4.0)'),
    ('bannister2017.pdf', 'bannister2017review',
     'https://centaur.reading.ac.uk/68685/7/qj2982.pdf',
     'A review of operational methods of variational and ensemble-variational data assimilation',
     'publisher PDF via CentAUR, University of Reading (Wiley host returns 403)'),
    ('martin2015.pdf', 'martin2015status',
     'https://ndownloader.figshare.com/files/40695647',
     'Status and future of data assimilation in operational oceanography',
     'publisher PDF via Figshare article 22957895 (T&F host returns 403)'),
    ('dong2017.pdf', 'dong2017impact',
     'https://repository.library.noaa.gov/view/noaa/17960/noaa_17960_DS1.pdf',
     'Impact of Assimilating Underwater Glider Data on Hurricane Gonzalo (2014) Forecasts',
     'publisher PDF via the NOAA Institutional Repository (AMS host returns an empty 202 to scripted fetches)'),
    # ---- non-anchor AI papers (prompts #2-#3, DA37)
    ('bi2023.pdf', 'bi2023accurate',
     'https://www.nature.com/articles/s41586-023-06185-3.pdf',
     'Accurate medium-range global weather forecasting with 3D neural networks',
     'publisher PDF (Nature, CC BY 4.0)'),
    ('lam2023.pdf', 'lam2023learning',
     'https://arxiv.org/pdf/2212.12794',
     'GraphCast: Learning skillful medium-range global weather forecasting',
     'arXiv copy (Science version paywalled)'),
    ('lang2024.pdf', 'lang2024aifs',
     'https://arxiv.org/pdf/2406.01465',
     "AIFS - ECMWF's data-driven forecasting system",
     'arXiv (preprint only)'),
    ('price2024.pdf', 'price2024probabilistic',
     'https://www.nature.com/articles/s41586-024-08252-9.pdf',
     'Probabilistic weather forecasting with machine learning',
     'publisher PDF (Nature, CC BY 4.0)'),
    ('hatfield2021.pdf', 'hatfield2021building',
     'https://zenodo.org/api/records/7624565/files/J%20Adv%20Model%20Earth%20Syst%20-%202021%20-%20Hatfield%20-%20Building%20Tangent%E2%80%90Linear%20and%20Adjoint%20Models%20for%20Data%20Assimilation%20With%20Neural.pdf/content',
     'Building Tangent-Linear and Adjoint Models for Data Assimilation With Neural Networks',
     'publisher PDF via Zenodo record 7624565 (AGU host returns 403)'),
    ('xu2025.pdf', 'xu2025fuxida',
     'https://www.nature.com/articles/s41612-025-01039-3.pdf',
     'FuXi-DA: a generalized deep learning data assimilation framework for assimilating satellite observations',
     'publisher PDF (npj Clim. Atmos. Sci., CC BY-NC-ND 4.0)'),
    ('allen2025.pdf', 'allen2025endtoend',
     'https://www.nature.com/articles/s41586-025-08897-0.pdf',
     'End-to-end data-driven weather prediction',
     'publisher PDF (Nature, CC BY 4.0)'),
    ('alexe2024.pdf', 'alexe2024graphdop',
     'https://arxiv.org/pdf/2412.15687',
     'GraphDOP: Towards skilful data-driven medium-range weather forecasts learnt and initialised directly from observations',
     'arXiv (preprint only)'),
    ('manshausen2025.pdf', 'manshausen2025generative',
     'https://arxiv.org/pdf/2406.16947',
     'Generative Data Assimilation of Sparse Weather Station Observations at Kilometer Scales',
     'arXiv copy (AGU host returns 403)'),
    ('yuan2026.pdf', 'yuan2026samudra2',
     'https://arxiv.org/pdf/2606.02610',
     'Samudra 2: Scaling Ocean Emulators across Resolutions',
     'arXiv (preprint only)'),
    ('chattopadhyay2024.pdf', 'chattopadhyay2024oceannet',
     'https://www.nature.com/articles/s41598-024-72145-0.pdf',
     'OceanNet: a principled neural operator-based digital twin for regional oceans',
     'publisher PDF (Sci. Rep., CC BY 4.0)'),
    ('gregory2023.pdf', 'gregory2023deep',
     'https://arxiv.org/pdf/2304.03832',
     'Deep learning of systematic sea ice model errors from data assimilation increments',
     'arXiv copy (AGU host returns 403)'),
    ('fablet2021.pdf', 'fablet2021learning',
     'https://arxiv.org/pdf/2007.12941',
     'Learning Variational Data Assimilation Models and Solvers',
     'arXiv copy (AGU host returns 403)'),
    ('beauchamp2023.pdf', 'beauchamp2023fourdvarnet',
     'https://gmd.copernicus.org/articles/16/2119/2023/gmd-16-2119-2023.pdf',
     '4DVarNet-SSH: end-to-end learning of variational interpolation schemes for nadir and wide-swath satellite altimetry',
     'publisher PDF (Copernicus, CC BY 4.0)'),
    ('martin2023.pdf', 'martin2023synthesizing',
     'https://eartharxiv.org/repository/object/4844/download/10568/',
     'Synthesizing Sea Surface Temperature and Satellite Altimetry Observations Using Deep Learning Improves the Accuracy and Resolution of Gridded Sea Surface Height Anomalies',
     'EarthArXiv copy (AGU host returns 403)'),
    ('sugiura2020.pdf', 'sugiura2020machine',
     'https://arxiv.org/pdf/1907.00500',
     'Machine Learning Technique Using the Signature Method for Automated Quality Control of Argo Profiles',
     'arXiv copy (AGU host returns 403)'),
    ('bittig2018.pdf', 'bittig2018canyonb',
     'https://www.frontiersin.org/articles/10.3389/fmars.2018.00328/pdf',
     'An Alternative to Static Climatologies: Robust Estimation of Open Ocean CO2 Variables and Nutrient Concentrations From T, S, and O2 Data Using Bayesian Neural Networks',
     'publisher PDF (Frontiers, CC BY 4.0)'),
    ('gloege2022.pdf', 'gloege2022improved',
     'https://repository.library.noaa.gov/view/noaa/59204/noaa_59204_DS1.pdf',
     'Improved Quantification of Ocean Carbon Uptake by Using Machine Learning to Merge Global Models and pCO2 Data',
     'publisher PDF via the NOAA Institutional Repository (AGU host returns 403)'),
    # ---- added for the glider section (prompt #6, DA53)
    ('mattern2026.pdf', 'mattern2026improving',
     'https://bg.copernicus.org/articles/23/2621/2026/bg-23-2621-2026.pdf',
     'Improving coastal ocean pH estimates through assimilation of glider observations and hybrid statistical methods',
     'publisher PDF (Copernicus, CC BY 4.0)'),
]


def words(text):
    """ Lower-case alphanumeric tokens of a string. Generated by JXP and Claude """
    return [w for w in re.split(r'[^a-z0-9]+', text.lower()) if len(w) > 2]


def title_match(path, title):
    """ Fraction of the title's words found in the first two pages of the PDF.

    Parameters
    ----------
    path : str, PDF file
    title : str, expected title

    Returns
    -------
    float in [0, 1]; 0 if pdftotext fails

    Generated by JXP and Claude
    """
    try:
        txt = subprocess.run(['pdftotext', '-l', '2', path, '-'], capture_output=True,
                             text=True, timeout=120).stdout
    except Exception:
        return 0.0
    # pdftotext splits hyphenated words across lines; drop the hyphens before matching
    have = set(words(txt.replace('-\n', '').replace('‐', '-')))
    want = words(title)
    return sum(w in have for w in want) / max(1, len(want))


def is_pdf(path):
    """ True if `file` identifies the path as a PDF document. Generated by JXP and Claude """
    out = subprocess.run(['file', '-b', path], capture_output=True, text=True).stdout
    return out.startswith('PDF document')


def fetch(url, path):
    """ Download url to path with curl, following redirects. Returns the HTTP code. Generated by JXP and Claude """
    res = subprocess.run(['curl', '-sS', '-L', '-A', UA, '--max-time', '300', '-o', path,
                          '-w', '%{http_code}', url], capture_output=True, text=True)
    return res.stdout.strip()


def main():
    """ Fetch and check every PDF in the list; exit non-zero if any fails. Generated by JXP and Claude """
    ap = argparse.ArgumentParser()
    ap.add_argument('--force', action='store_true', help='re-fetch files that already exist')
    ap.add_argument('--only', default='', help='comma-separated reading-list keys to fetch')
    args = ap.parse_args()
    only = set(k for k in args.only.split(',') if k)
    os.makedirs(DEST, exist_ok=True)
    bad = []
    print(f'# fetch_pdfs.py -> {DEST}')
    for fname, key, url, title, kind in PDFS:
        if only and key not in only:
            continue
        path = os.path.join(DEST, fname)
        if os.path.exists(path) and not args.force:
            code = 'kept'
        else:
            code = fetch(url, path)
        ok_pdf = os.path.exists(path) and is_pdf(path)
        frac = title_match(path, title) if ok_pdf else 0.0
        size = os.path.getsize(path) // 1024 if os.path.exists(path) else 0
        good = ok_pdf and frac >= 0.8
        print(f'{"ok  " if good else "FAIL"} {code:>4} {size:>7d} kB  title {frac:4.2f}  {fname:24s} {key:28s} {kind}')
        if not good:
            bad.append((fname, key, code, frac))
            if os.path.exists(path):
                os.remove(path)
    print(f'# {len(PDFS) - len(bad)}/{len(PDFS)} fetched and checked')
    for fname, key, code, frac in bad:
        print(f'# failed: {fname} ({key}) HTTP {code}, title match {frac:.2f}')
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
