""" Draw Figure 2 of da_ai_review.md: 2018-2026 milestones of AI in data assimilation.

Two tracks, numerical weather prediction (NWP) and ocean, each carrying the exemplars
that Sections 6 and 7 of the report cite.  Every milestone in MILESTONES below is dated
from a reference in ../sources.bib and carries that reference's BibTeX key; the script
refuses to run if a key is missing from sources.bib or if the date disagrees with what
the BibTeX record supports.  Three dating bases are used, and each milestone states its
own:

  'arxiv'  the month of the first arXiv version, read from the YYMM prefix of the
           `eprint` field (the preprint date; the journal year may be later);
  'month'  the `month` and `year` fields of the record: for journal articles the
           Crossref online-publication month that build_bib.py records (since
           2026-09-24, DA60), for grey items the month stated by the source (the day,
           where given, comes from the sources.md annotation of the same record);
  'year'   the record carries a year only, so the milestone is plotted at mid-year
           (1 July) and drawn with a bar spanning the whole year to say so (no
           milestone uses this basis since 2026-09-24; the code path is kept).

Marker colour gives the track and marker shape the taxonomy category of the report
(1 emulators/surrogates, 2 ML inside classical DA, 3 ML replacing DA, 4 ML around DA).
Labels alternate between the two sides of their track and are placed by a greedy
routine that measures each rendered label, tries increasing levels away from the track
and a few anchorings at each level, and accepts the first position where no box or
leader line crosses another (see place_labels), so nothing is drawn on top of anything
else; two milestones with the same date on one track have their markers nudged 32 days
apart for drawing only.  Colours are from the Okabe-Ito colour-blind-safe set.

Output: ../figs/ai_da_timeline.png (200 dpi, white background).

Usage (from reports/data_assimilation/, ocean14):
    conda run -n ocean14 python scripts/make_timeline.py

History: written 2026-09-24 (prompt #7); 24 milestones (11 NWP, 13 ocean), 14 dated
by arXiv month, 1 by a month field, 9 by year only.  Revised 2026-09-24 (prompt #8,
DA60): the nine year-only milestones moved to the `month` basis from the Crossref
published-online month now in sources.bib (Bonavita 2020-11, Hatfield 2021-09,
Pangu-Weather 2023-07, GenCast 2024-12, Aardvark 2025-03, CANYON-B 2018-09, LDEO-HPD
2022-01, Martin 2023-05, WenHai 2025-03); 14 arXiv, 10 month, 0 year.

Generated by JXP and Claude
"""
import datetime as dt
import os
import re
import sys

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402
import matplotlib.dates as mdates  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT_DIR = os.path.dirname(HERE)
BIB = os.path.join(REPORT_DIR, 'sources.bib')
OUT = os.path.join(REPORT_DIR, 'figs', 'ai_da_timeline.png')

# ---------------------------------------------------------------------------
# Editable data.  One tuple per milestone:
#   (date 'YYYY-MM-DD', track 'nwp'|'ocean', category 1-4, short label, BibTeX key, basis)
# basis is 'arxiv' (month of arXiv v1 from the eprint field), 'month' (month field of
# the record) or 'year' (year only; plotted at 1 July with a bar over the year).
# ---------------------------------------------------------------------------
MILESTONES = [
    # --- NWP track (Section 6) ---
    ('2020-11-01', 'nwp', 2, 'Learned model error inside 4D-Var\n(Bonavita & Laloyaux 2020)', 'bonavita2020machine', 'month'),
    ('2021-09-01', 'nwp', 2, 'Neural TL and adjoint in 4D-Var\n(Hatfield et al. 2021)', 'hatfield2021building', 'month'),
    ('2022-12-01', 'nwp', 1, 'GraphCast (Lam et al. 2023)', 'lam2023learning', 'arxiv'),
    ('2023-07-01', 'nwp', 1, 'Pangu-Weather (Bi et al. 2023)', 'bi2023accurate', 'month'),
    ('2024-04-01', 'nwp', 3, 'FuXi-DA, learned radiance DA\n(Xu et al. 2025)', 'xu2025fuxida', 'arxiv'),
    ('2024-06-01', 'nwp', 1, 'AIFS described (Lang et al. 2024)', 'lang2024aifs', 'arxiv'),
    ('2024-06-01', 'nwp', 3, 'Generative DA of stations\n(Manshausen et al. 2025)', 'manshausen2025generative', 'arxiv'),
    ('2024-12-01', 'nwp', 1, 'GenCast (Price et al. 2024)', 'price2024probabilistic', 'month'),
    ('2024-12-01', 'nwp', 3, 'GraphDOP, observations only\n(Alexe et al. 2024)', 'alexe2024graphdop', 'arxiv'),
    ('2025-02-25', 'nwp', 1, 'AIFS Single operational\n(ECMWF 2025)', 'ecmwf2025aifs', 'month'),
    ('2025-03-01', 'nwp', 3, 'Aardvark end-to-end\n(Allen et al. 2025)', 'allen2025endtoend', 'month'),
    # --- Ocean track (Section 7) ---
    ('2018-09-01', 'ocean', 4, 'CANYON-B (Bittig et al. 2018)', 'bittig2018canyonb', 'month'),
    ('2019-07-01', 'ocean', 4, 'Argo ML quality control\n(Sugiura & Hosoda 2020)', 'sugiura2020machine', 'arxiv'),
    ('2020-07-01', 'ocean', 3, '4DVarNet on Lorenz systems\n(Fablet et al. 2021)', 'fablet2021learning', 'arxiv'),
    ('2022-01-01', 'ocean', 2, 'LDEO-HPD pCO2 misfit correction\n(Gloege et al. 2022)', 'gloege2022improved', 'month'),
    ('2022-11-01', 'ocean', 3, '4DVarNet-SSH OSSE\n(Beauchamp et al. 2023)', 'beauchamp2023fourdvarnet', 'arxiv'),
    ('2023-04-01', 'ocean', 2, 'Learned sea-ice increments\n(Gregory et al. 2023)', 'gregory2023deep', 'arxiv'),
    ('2023-05-01', 'ocean', 3, 'SSH mapping OSE, withheld CryoSat-2\n(Martin et al. 2023)', 'martin2023synthesizing', 'month'),
    ('2023-10-01', 'ocean', 1, 'OceanNet regional emulator\n(Chattopadhyay et al. 2024)', 'chattopadhyay2024oceannet', 'arxiv'),
    ('2024-02-01', 'ocean', 1, 'XiHe 1/12 deg emulator\n(Wang et al. 2024)', 'wang2024xihe', 'arxiv'),
    ('2024-12-01', 'ocean', 1, 'Samudra (Dheeshjith et al. 2025)', 'dheeshjith2025samudra', 'arxiv'),
    ('2024-12-01', 'ocean', 1, 'GLONET, pre-operational\n(El Aouni et al. 2025)', 'elaouni2025glonet', 'arxiv'),
    ('2025-03-01', 'ocean', 1, 'WenHai vs GLO12v4 (Cui et al. 2025)', 'cui2025forecasting', 'month'),
    ('2026-06-01', 'ocean', 1, 'Samudra 2 (Yuan et al. 2026)', 'yuan2026samudra2', 'arxiv'),
]

# Okabe-Ito colour-blind-safe set (blue, vermillion) and greys.
TRACKS = {
    'nwp': dict(y=1.7, color='#0072B2', name='NWP'),
    'ocean': dict(y=-1.7, color='#D55E00', name='Ocean'),
}
CATEGORY_MARKERS = {1: 'o', 2: 's', 3: 'D', 4: '^'}
CATEGORY_NAMES = {
    1: '(1) emulators / surrogates of the model',
    2: '(2) ML inside classical DA',
    3: '(3) ML replacing DA',
    4: '(4) ML around DA (QC, transfer functions)',
}
MONTHS = {m: i for i, m in enumerate(
    ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'], 1)}

X0, X1 = dt.date(2017, 7, 1), dt.date(2027, 2, 1)
LEVEL_STEP = 0.36      # vertical distance between label levels (data units)
FIRST_LEVEL = 0.48     # distance of the first level from the track line
MAX_LEVELS = 9
FONT = 7.6


def parse_bib(path):
    """ Return {key: {field: value}} for every record in a BibTeX file.

    Generated by JXP and Claude """
    with open(path) as fh:
        text = fh.read()
    records = {}
    for m in re.finditer(r'^@(\w+)\{([^,\s]+),(.*?)^\}', text, flags=re.M | re.S):
        fields = {}
        for f in re.finditer(r'^\s*(\w+)\s*=\s*\{(.*?)\},?\s*$', m.group(3), flags=re.M):
            fields[f.group(1).lower()] = f.group(2)
        records[m.group(2)] = fields
    return records


def check_milestone(date, key, basis, rec):
    """ Raise if the milestone date is not supported by the BibTeX record.

    Generated by JXP and Claude """
    year = int(rec.get('year', '0'))
    if basis == 'year':
        if (date.year, date.month, date.day) != (year, 7, 1):
            raise ValueError(f"{key}: basis 'year' requires {year}-07-01, got {date}")
    elif basis == 'arxiv':
        eprint = rec.get('eprint', '')
        if not re.match(r'^\d{4}\.\d{4,5}$', eprint):
            raise ValueError(f"{key}: basis 'arxiv' but no new-style eprint field ({eprint!r})")
        yy, mm = int(eprint[:2]) + 2000, int(eprint[2:4])
        if (date.year, date.month) != (yy, mm):
            raise ValueError(f"{key}: eprint {eprint} gives {yy}-{mm:02d}, got {date}")
    elif basis == 'month':
        mon = rec.get('month', '').strip().lower()[:3]
        if mon not in MONTHS:
            raise ValueError(f"{key}: basis 'month' but month field is {rec.get('month')!r}")
        if (date.year, date.month) != (year, MONTHS[mon]):
            raise ValueError(f"{key}: record gives {year}-{MONTHS[mon]:02d}, got {date}")
    else:
        raise ValueError(f"{key}: unknown basis {basis!r}")


def load_milestones():
    """ Validate MILESTONES against sources.bib and return them with date objects.

    Generated by JXP and Claude """
    bib = parse_bib(BIB)
    out = []
    for date_s, track, cat, label, key, basis in MILESTONES:
        if key not in bib:
            sys.exit(f"ERROR: key {key!r} is not in {BIB}")
        if track not in TRACKS or cat not in CATEGORY_MARKERS:
            sys.exit(f"ERROR: bad track or category for {key}")
        date = dt.date.fromisoformat(date_s)
        try:
            check_milestone(date, key, basis, bib[key])
        except ValueError as err:
            sys.exit(f"ERROR: {err}")
        out.append(dict(date=date, track=track, cat=cat, label=label, key=key, basis=basis))
    out.sort(key=lambda m: m['date'])
    # two milestones on one track with the same date: nudge the second by 32 days so the
    # markers and leaders stay distinct (the date itself is unchanged in MILESTONES)
    for i, m in enumerate(out):
        x = m['date']
        taken = [o['x'] for o in out[:i] if o['track'] == m['track']]
        while x in taken:
            x = x + dt.timedelta(days=32)
        m['x'] = x
    # labels alternate between the two sides of each track, in date order, so that each
    # side carries every other milestone (outer side first: above NWP, below ocean)
    count = {t: 0 for t in TRACKS}
    for m in out:
        outer = 1 if m['track'] == 'nwp' else -1
        m['side'] = outer if count[m['track']] % 2 == 0 else -outer
        count[m['track']] += 1
    return out


def _segment_hits_box(x0, y0, x1, y1, bb, pad):
    """ True if the segment (x0,y0)-(x1,y1) passes through bbox `bb` widened by `pad` in x.

    Liang-Barsky clipping against the rectangle.  Generated by JXP and Claude """
    xlo, xhi, ylo, yhi = bb.x0 - pad, bb.x1 + pad, min(bb.y0, bb.y1), max(bb.y0, bb.y1)
    dx, dy = x1 - x0, y1 - y0
    t0, t1 = 0.0, 1.0
    for p_, q_ in ((-dx, x0 - xlo), (dx, xhi - x0), (-dy, y0 - ylo), (dy, yhi - y0)):
        if p_ == 0:
            if q_ < 0:
                return False
            continue
        t = q_ / p_
        if p_ < 0:
            t0 = max(t0, t)
        else:
            t1 = min(t1, t)
        if t0 > t1:
            return False
    return True


def place_labels(ax, fig, items):
    """ Place labels above (NWP) or below (ocean) the track without overlaps.

    Labels alternate between the two sides of their track and are placed in date
    order.  Each is tried at increasing levels away from its
    track and, at each level, at a short list of anchorings (box ending at the marker,
    centred on it, starting at it, and small horizontal offsets of each); a slanted
    leader line joins marker and box.  A position is accepted when the box clears every
    box already placed, no leader already drawn crosses the new box, the new leader
    crosses no box already placed, and the box does not sit over the x of a marker on
    the same track whose label is still to be placed (so that later labels keep a free
    path); the last rule is dropped in a second pass only if nothing else fits.  The
    gap between the track and the first label level (FIRST_LEVEL) is what lets a leader
    step sideways.  Returns the highest level used.

    Generated by JXP and Claude """
    renderer = fig.canvas.get_renderer()
    placed = []                               # (bbox, leader segment) per placed label
    track_ys = [tr['y'] for tr in TRACKS.values()]
    xmin, xmax = ax.get_xlim()
    pad = 0.004 * (xmax - xmin)
    year = 365.25
    anchors = [('right', 0.0), ('right', 0.15), ('center', 0.0), ('center', -0.4), ('center', 0.4),
               ('left', 0.0), ('left', -0.15), ('right', 0.3), ('left', -0.3), ('right', 0.5),
               ('left', -0.5), ('center', -0.8), ('center', 0.8)]
    for n, it in enumerate(items):
        tr = TRACKS[it['track']]
        sign = it['side']
        x = mdates.date2num(it['x'])
        y_mark = tr['y'] + sign * 0.07
        va = 'bottom' if sign > 0 else 'top'
        later = [mdates.date2num(o['x']) for o in items[n + 1:]
                 if o['track'] == it['track'] and o['side'] == it['side']]
        txt, done = None, False
        for strict in (True, False):
            for lev in range(MAX_LEVELS):
                y = tr['y'] + sign * (FIRST_LEVEL + lev * LEVEL_STEP)
                for ha, dx in anchors:
                    xa = x + dx * year
                    if txt is not None:
                        txt.remove()
                    txt = ax.text(xa, y, it['label'], fontsize=FONT, ha=ha, va=va, color='#222222',
                                  linespacing=1.15, zorder=5)
                    bb = txt.get_window_extent(renderer).transformed(ax.transData.inverted())
                    if bb.x0 < xmin + pad or bb.x1 > xmax - pad:
                        continue          # outside the frame
                    if any(bb.y0 - 0.12 < ty < bb.y1 + 0.12 for ty in track_ys if ty != tr['y']):
                        continue          # would sit on the other track's line
                    if strict and any(bb.x0 - pad < lx < bb.x1 for lx in later):
                        continue          # would sit over a later marker on this track
                    y_edge = (bb.y0 if sign > 0 else bb.y1) - sign * 0.015
                    seg = (x, y_mark, xa, y_edge)
                    clash = False
                    for (obb, oseg) in placed:
                        if not (bb.x1 + pad < obb.x0 or bb.x0 - pad > obb.x1 or
                                bb.y1 < obb.y0 or bb.y0 > obb.y1):
                            clash = True  # boxes overlap
                        elif _segment_hits_box(*oseg, bb, pad):
                            clash = True  # an existing leader crosses the new box
                        elif _segment_hits_box(*seg, obb, pad):
                            clash = True  # the new leader crosses an existing box
                        if clash:
                            break
                    if not clash:
                        placed.append((bb, seg))
                        it['level'] = lev
                        done = True
                        break
                if done:
                    break
            if done:
                break
        if not done:
            for (obb, oseg) in placed:
                print(f"  placed: x {mdates.num2date(obb.x0).date()}..{mdates.num2date(obb.x1).date()} "
                      f"y {obb.y0:.2f}..{obb.y1:.2f}; leader x {mdates.num2date(oseg[0]).date()}"
                      f"->{mdates.num2date(oseg[2]).date()} y {oseg[1]:.2f}->{oseg[3]:.2f}")
            sys.exit(f"ERROR: could not place label for {it['key']} ({it['x']}) within {MAX_LEVELS} levels")
        ax.plot([seg[0], seg[2]], [seg[1], seg[3]], color='#9a9a9a', lw=0.6, zorder=2)
    ylo = min(min(bb.y0 for bb, _ in placed), min(track_ys))
    yhi = max(max(bb.y1 for bb, _ in placed), max(track_ys))
    return max(i['level'] for i in items), (ylo, yhi)


def main():
    """ Generated by JXP and Claude """
    items = load_milestones()
    n_nwp = sum(i['track'] == 'nwp' for i in items)
    print(f"{len(items)} milestones ({n_nwp} NWP, {len(items) - n_nwp} ocean); "
          f"bases: " + ', '.join(f"{b} {sum(i['basis'] == b for i in items)}" for b in ('arxiv', 'month', 'year')))

    fig, ax = plt.subplots(figsize=(13.0, 8.2), dpi=200, facecolor='white')
    ax.set_facecolor('white')
    ax.set_xlim(mdates.date2num(X0), mdates.date2num(X1))
    ax.set_ylim(TRACKS['ocean']['y'] - (FIRST_LEVEL + 4 * LEVEL_STEP) - 0.15,
                TRACKS['nwp']['y'] + (FIRST_LEVEL + 4 * LEVEL_STEP) + 0.15)

    # year grid and tracks
    for yr in range(2018, 2027):
        ax.axvline(mdates.date2num(dt.date(yr, 1, 1)), color='#e6e6e6', lw=0.7, zorder=0)
    for t, tr in TRACKS.items():
        ax.axhline(tr['y'], color=tr['color'], lw=1.6, alpha=0.55, zorder=1)
        ax.text(mdates.date2num(X0) - 0.012 * (mdates.date2num(X1) - mdates.date2num(X0)), tr['y'], tr['name'],
                ha='right', va='center', fontsize=10, fontweight='bold', color=tr['color'])

    # markers (with a year-span bar for year-only dates)
    for it in items:
        tr = TRACKS[it['track']]
        x = mdates.date2num(it['x'])
        if it['basis'] == 'year':
            ax.plot([mdates.date2num(dt.date(it['date'].year, 1, 1)),
                     mdates.date2num(dt.date(it['date'].year, 12, 31))],
                    [tr['y'], tr['y']], color=tr['color'], lw=5, alpha=0.18, solid_capstyle='butt', zorder=1)
        ax.plot(x, tr['y'], marker=CATEGORY_MARKERS[it['cat']], ms=7.0, mfc=tr['color'], mec='white',
                mew=0.9, ls='none', zorder=4)

    fig.canvas.draw()
    top, (ylo, yhi) = place_labels(ax, fig, items)
    print(f"labels placed on {top + 1} levels at most")
    # trim the empty space above and below the labels, keeping the same data units per
    # inch (so the placement just checked stays valid): shrink ylim and the figure height
    # together
    y0, y1 = ax.get_ylim()
    new_lo, new_hi = ylo - 0.15, yhi + 0.15
    ax.set_ylim(new_lo, new_hi)
    w, h = fig.get_size_inches()
    fig.set_size_inches(w, h * (new_hi - new_lo) / (y1 - y0) + 0.9)

    # axes cosmetics
    ax.xaxis.set_major_locator(mdates.YearLocator())
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y'))
    ax.tick_params(axis='x', labelsize=9, length=3, colors='#444444')
    ax.set_yticks([])
    for side in ('left', 'right', 'top'):
        ax.spines[side].set_visible(False)
    ax.spines['bottom'].set_color('#888888')

    # legend: shape = category, colour = track, bar = year-only date
    handles = [Line2D([], [], marker=CATEGORY_MARKERS[c], ls='none', ms=7, mfc='#666666', mec='white',
                      label=CATEGORY_NAMES[c]) for c in (1, 2, 3, 4)]
    if any(i['basis'] == 'year' for i in items):
        handles.append(Line2D([], [], color='#666666', lw=5, alpha=0.25,
                              label='year-only date: plotted at mid-year, bar spans the year'))
    fig.legend(handles=handles, loc='lower center', fontsize=7.6, frameon=False, ncol=3,
               handletextpad=0.6, columnspacing=1.6, title='marker shape gives the taxonomy category; '
               'colour the track', title_fontsize=7.6, bbox_to_anchor=(0.5, 0.0))
    ax.set_title('AI in data assimilation, 2018-2026: exemplars cited in Sections 6 (NWP) and 7 (ocean)',
                 fontsize=10.5, loc='left', color='#222222', pad=8)

    fig.tight_layout(rect=(0, 0.10, 1, 1))
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    fig.savefig(OUT, dpi=200, facecolor='white')
    print(f"wrote {OUT}")


if __name__ == '__main__':
    main()
