#!/usr/bin/env python
"""Verify the DOIs in reading_list.md by HEAD request against https://doi.org/<doi>.

Generated by JXP and Claude.

Reads ``reports/data_assimilation/reading_list.md`` (or the file given as the first
argument), extracts every DOI that appears as ``doi:<doi>`` or as a
``https://doi.org/<doi>`` link, runs ``curl -sI https://doi.org/<doi>`` for each
(one attempt, 30 s timeout), and prints one line per DOI with the HTTP status code
and the ``Location`` header. A DOI counts as verified when the status is a 30x
redirect, which is the convention of the El Nino 2026 ``sources.md``
(``curl -sI https://doi.org/<doi>`` returning a redirect on the access date).

Usage::

    conda run -n ocean14 python reports/data_assimilation/scripts/verify_reading_list_dois.py

The script does not modify any file; the statuses in ``reading_list.md`` are set by
hand from its output. It exits with status 1 if any DOI fails to redirect, so it can
be used as a check.
"""
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT = HERE.parent / "reading_list.md"
DOI_RE = re.compile(r"(?:doi:|https?://doi\.org/)(10\.\d{4,9}/[^\s|`\]>]+)")


def extract_dois(text):
    """Return the DOIs in `text`, in order of first appearance, without duplicates.

    Parentheses are legal inside a DOI (e.g. the TAO journal's
    ``10.3319/TAO.2009.04.16.01(IWNOP)``), so a closing parenthesis is kept when it
    balances an opening one and stripped when it only closes the surrounding text.
    """
    seen = []
    for m in DOI_RE.finditer(text):
        doi = m.group(1).rstrip(".,;")
        while doi.endswith(")") and doi.count(")") > doi.count("("):
            doi = doi[:-1]
        if doi not in seen:
            seen.append(doi)
    return seen


def head(doi, timeout=30):
    """HEAD request against doi.org; return (status_code or None, location or '')."""
    cmd = ["curl", "-sI", "-m", str(timeout), f"https://doi.org/{doi}"]
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout + 5).stdout
    except (subprocess.TimeoutExpired, OSError):
        return None, ""
    status, location = None, ""
    for line in out.splitlines():
        if line.upper().startswith("HTTP/"):
            parts = line.split()
            if len(parts) > 1 and parts[1].isdigit():
                status = int(parts[1])
        elif line.lower().startswith("location:"):
            location = line.split(":", 1)[1].strip()
    return status, location


def main(argv):
    path = Path(argv[1]) if len(argv) > 1 else DEFAULT
    text = path.read_text(encoding="utf-8")
    dois = extract_dois(text)
    print(f"# {path.name}: {len(dois)} DOIs, checked {date.today().isoformat()}")
    n_ok = 0
    failed = []
    for doi in dois:
        status, location = head(doi)
        ok = status is not None and 300 <= status < 400
        n_ok += ok
        if not ok:
            failed.append(doi)
        flag = "ok  " if ok else "FAIL"
        print(f"{flag} {status if status is not None else 'no-response':>11}  {doi:45s} {location}")
    print(f"# {n_ok}/{len(dois)} redirected (30x)")
    if failed:
        print("# not verified: " + ", ".join(failed))
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
